module Hecks
  module ValidationRules
    module Naming

    # Hecks::ValidationRules::Naming::ReservedNames
    #
    # Validates that attribute names are not Ruby keywords and that aggregate
    # names form valid Ruby constants. Also provides a class method for
    # generating non-blocking warnings about reserved attribute names (+id+,
    # +created_at+, +updated_at+) that override auto-generated fields.
    #
    # Part of the ValidationRules::Naming group -- run by +Hecks.validate+.
    #
    class ReservedNames < BaseRule
      # Checks aggregate names for valid Ruby constant format and attribute
      # names for Ruby keyword conflicts.
      #
      # @return [Array<String>] error messages for invalid names
      def errors
        errs = []
        @domain.aggregates.each do |agg|
          errs.concat(check_aggregate_name(agg))
          errs.concat(check_keyword_attrs(agg))
        end
        errs
      end

      # Returns warnings (not errors) for reserved attribute names (+id+,
      # +created_at+, +updated_at+). These attributes are auto-generated by
      # +Hecks::Model+, so declaring them explicitly may cause unexpected
      # behavior. Called by +Hecks.build+ to emit non-blocking warnings.
      #
      # @param domain [Hecks::BluebookModel::Structure::Domain] the domain to check
      # @return [Array<String>] warning messages for reserved attribute overrides
      def self.reserved_attr_warnings(domain)
        warnings = []
        domain.aggregates.each do |agg|
          agg.attributes.each do |attr|
            if Hecks::Utils::RESERVED_AGGREGATE_ATTRS.include?(attr.name.to_s)
              warnings << "#{agg.name} attribute '#{attr.name}' overrides auto-generated attribute — make sure this is intentional"
            end
          end
        end
        warnings
      end

      private

      # Validates that the aggregate name is a valid Ruby constant: starts with
      # an uppercase letter and contains only alphanumeric characters.
      #
      # @param agg [Hecks::BluebookModel::Structure::Aggregate] the aggregate to check
      # @return [Array<String>] error messages (empty if valid)
      def check_aggregate_name(agg)
        errs = []
        unless agg.name =~ /\A[A-Z][a-zA-Z0-9]*\z/
          errs << error("Invalid aggregate name '#{agg.name}': must start with uppercase letter and contain only alphanumeric characters",
            hint: "Rename to PascalCase, e.g. '#{agg.name.capitalize.gsub(/[^a-zA-Z0-9]/, '')}'")
        end
        errs
      end

      # Validates that no attribute name is a Ruby keyword (e.g. +class+,
      # +def+, +end+). Ruby keywords cannot be used as method names without
      # causing syntax errors.
      #
      # @param agg [Hecks::BluebookModel::Structure::Aggregate] the aggregate to check
      # @return [Array<String>] error messages for keyword attribute names
      def check_keyword_attrs(agg)
        errs = []
        agg.attributes.each do |attr|
          if Hecks::Utils.ruby_keyword?(attr.name.to_s)
            errs << error("#{agg.name} attribute '#{attr.name}' is a Ruby keyword",
              hint: "Rename to a non-keyword name, e.g. '#{attr.name}_value' or '#{agg.name.downcase}_#{attr.name}'")
          end
        end
        errs
      end
    end
    Hecks.register_validation_rule(ReservedNames)
    end
  end
end
