module Hecks
  module Generators
    module Infrastructure
      class DomainGemGenerator < Hecks::Generator
        # Hecks::Generators::Infrastructure::DomainGemGenerator::FileWriter
        #
        # Mixin that writes generated domain files to disk — aggregates, value objects,
        # commands, events, policies, queries, ports, adapters, gemspec, entry point,
        # and Bluebook (serialized DSL). Preserves custom call methods in
        # command files across regeneration cycles. Part of DomainGemGenerator,
        # consumed by DomainGemGenerator#generate.
        #
        #   # Mixed into DomainGemGenerator:
        #   generate_aggregates(root, gem_name, mod)
        #
        module FileWriter
          include HecksTemplating::NamingHelpers
          private

          # Writes the +.gemspec+ file for the domain gem.
          #
          # @param root [String] absolute path to the gem root directory
          # @param gem_name [String] snake_case gem name (e.g. +"pizzas_domain"+)
          # @param mod [String] PascalCase domain module name (e.g. +"PizzasDomain"+)
          # @return [void]
          def generate_gemspec(root, gem_name, mod)
            gem_version = @domain.version || @version
            write_file(root, "#{gem_name}.gemspec", <<~RUBY)
              Gem::Specification.new do |s|
                s.name = "#{gem_name}"; s.version = "#{gem_version}"
                s.authors = ["Generated by Hecks"]; s.summary = "#{@domain.name} domain model"
                s.description = "Pure domain gem generated by Hecks"; s.license = "MIT"
                s.files = Dir["lib/**/*", "docs/**/*", "*Bluebook", "verbs.txt"]; s.require_paths = ["lib"]
                s.required_ruby_version = ">= 3.0"
                s.add_dependency "hecks"
                s.add_development_dependency "rspec", "~> 3.0"
              end
            RUBY
          end

          # Writes the autoload entry point file (+lib/<gem_name>.rb+) by
          # delegating to +AutoloadGenerator#generate_entry_point+.
          #
          # @param root [String] absolute path to the gem root directory
          # @param gem_name [String] snake_case gem name
          # @param mod [String] PascalCase domain module name
          # @return [void]
          def generate_entry_point(root, gem_name, mod)
            write_file(root, "lib/#{gem_name}.rb", AutoloadGenerator.new(@domain).generate_entry_point)
          end

          # Writes all aggregate-related files: the aggregate class itself (with
          # injected autoloads), value objects, entities, commands (preserving
          # custom +call+ methods), events, policies, subscribers, specifications,
          # and lifecycle definitions. Also creates conventional empty subdirectories
          # (+commands/+, +events/+, +policies/+, +queries/+, +subscribers/+,
          # +specifications/+) even when no files exist for those categories.
          #
          # @param root [String] absolute path to the gem root directory
          # @param gem_name [String] snake_case gem name
          # @param mod [String] PascalCase domain module name
          # @return [void]
          def generate_aggregates(root, gem_name, mod)
            @domain.aggregates.each do |agg|
              safe_name = bluebook_constant_name(agg.name)
              snake = bluebook_snake_name(safe_name)
              base = "lib/#{gem_name}/#{snake}"

              agg_gen = Domain::AggregateGenerator.new(agg, domain_module: mod)
              autoload_gen = AutoloadGenerator.new(@domain)
              autoloads = autoload_gen.generate_aggregate_autoloads(agg, gem_name, mod)

              agg_code = agg_gen.generate
              agg_code = inject_autoloads(agg_code, autoloads, safe_name)
              write_file(root, "#{base}/#{snake}.rb", agg_code)

              agg.value_objects.each do |vo|
                vo_gen = Domain::ValueObjectGenerator.new(vo, domain_module: mod, aggregate_name: safe_name)
                write_file(root, "#{base}/#{bluebook_snake_name(vo.name)}.rb", vo_gen.generate)
              end

              agg.entities.each do |ent|
                ent_gen = Domain::EntityGenerator.new(ent, domain_module: mod, aggregate_name: safe_name)
                write_file(root, "#{base}/#{bluebook_snake_name(ent.name)}.rb", ent_gen.generate)
              end

              agg.commands.each_with_index do |cmd, i|
                cmd_gen = Domain::CommandGenerator.new(cmd, domain_module: mod, aggregate_name: safe_name, aggregate: agg, event: agg.events[i])
                cmd_path = "#{base}/commands/#{bluebook_snake_name(cmd.name)}.rb"
                write_command_file(root, cmd_path, cmd_gen.generate, cmd)
              end

              agg.events.each do |evt|
                evt_gen = Domain::EventGenerator.new(evt, domain_module: mod, aggregate_name: safe_name)
                write_file(root, "#{base}/events/#{bluebook_snake_name(evt.name)}.rb", evt_gen.generate)
              end

              agg.policies.each do |pol|
                pol_gen = Domain::PolicyGenerator.new(pol, domain_module: mod, aggregate_name: safe_name)
                write_file(root, "#{base}/policies/#{bluebook_snake_name(pol.name)}.rb", pol_gen.generate)
              end

              agg.subscribers.each do |sub|
                sub_gen = Domain::SubscriberGenerator.new(sub, domain_module: mod, aggregate_name: safe_name)
                write_file(root, "#{base}/subscribers/#{bluebook_snake_name(sub.name)}.rb", sub_gen.generate)
              end

              agg.specifications.each do |spec|
                spec_gen = Domain::SpecificationGenerator.new(spec, domain_module: mod, aggregate_name: safe_name)
                write_file(root, "#{base}/specifications/#{bluebook_snake_name(spec.name)}.rb", spec_gen.generate)
              end

              if agg.lifecycle
                lc_gen = Domain::LifecycleGenerator.new(agg.lifecycle, domain_module: mod, aggregate_name: safe_name)
                write_file(root, "#{base}/lifecycle.rb", lc_gen.generate)
              end

              # Create conventional folders even when empty
              %w[commands events policies queries subscribers specifications].each do |dir|
                FileUtils.mkdir_p(File.join(root, base, dir))
              end
            end
          end

          # Writes query files for every aggregate into their respective
          # +queries/+ subdirectories.
          #
          # @param root [String] absolute path to the gem root directory
          # @param gem_name [String] snake_case gem name
          # @param mod [String] PascalCase domain module name
          # @return [void]
          def generate_queries(root, gem_name, mod)
            @domain.aggregates.each do |agg|
              safe = bluebook_constant_name(agg.name)
              snake = bluebook_snake_name(safe)
              agg.queries.each do |q|
                write_file(root, "lib/#{gem_name}/#{snake}/queries/#{bluebook_snake_name(q.name)}.rb",
                           Domain::QueryGenerator.new(q, domain_module: mod, aggregate_name: safe).generate)
              end
            end
          end

          # Writes repository port interface modules for every aggregate into
          # the +ports/+ directory.
          #
          # @param root [String] absolute path to the gem root directory
          # @param gem_name [String] snake_case gem name
          # @param mod [String] PascalCase domain module name
          # @return [void]
          def generate_ports(root, gem_name, mod)
            @domain.aggregates.each do |agg|
              snake = bluebook_snake_name(bluebook_constant_name(agg.name))
              write_file(root, "lib/#{gem_name}/ports/#{snake}_repository.rb",
                         Infrastructure::PortGenerator.new(agg, domain_module: mod).generate)
            end
          end

          # Writes in-memory repository adapter classes for every aggregate into
          # the +adapters/+ directory.
          #
          # @param root [String] absolute path to the gem root directory
          # @param gem_name [String] snake_case gem name
          # @param mod [String] PascalCase domain module name
          # @return [void]
          def generate_adapters(root, gem_name, mod)
            @domain.aggregates.each do |agg|
              snake = bluebook_snake_name(bluebook_constant_name(agg.name))
              write_file(root, "lib/#{gem_name}/adapters/#{snake}_memory_repository.rb",
                         Infrastructure::MemoryAdapterGenerator.new(agg, domain_module: mod).generate)
            end
          end

          # Writes workflow files into the +workflows/+ directory.
          #
          # @param root [String] absolute path to the gem root directory
          # @param gem_name [String] snake_case gem name
          # @param mod [String] PascalCase domain module name
          # @return [void]
          def generate_workflows(root, gem_name, mod)
            @domain.workflows.each do |wf|
              snake = bluebook_snake_name(wf.name)
              write_file(root, "lib/#{gem_name}/workflows/#{snake}.rb",
                         Domain::WorkflowGenerator.new(wf, domain_module: mod).generate)
            end
          end

          # Writes view files into the +views/+ directory.
          #
          # @param root [String] absolute path to the gem root directory
          # @param gem_name [String] snake_case gem name
          # @param mod [String] PascalCase domain module name
          # @return [void]
          def generate_views(root, gem_name, mod)
            @domain.views.each do |v|
              snake = bluebook_snake_name(v.name)
              write_file(root, "lib/#{gem_name}/views/#{snake}.rb",
                         Domain::ViewGenerator.new(v, domain_module: mod).generate)
            end
          end

          # Writes service files into the +services/+ directory.
          #
          # @param root [String] absolute path to the gem root directory
          # @param gem_name [String] snake_case gem name
          # @param mod [String] PascalCase domain module name
          # @return [void]
          def generate_services(root, gem_name, mod)
            @domain.services.each do |svc|
              snake = bluebook_snake_name(svc.name)
              write_file(root, "lib/#{gem_name}/services/#{snake}.rb",
                         Domain::ServiceGenerator.new(svc, domain_module: mod).generate)
            end
          end

          # Writes the serialized DSL file (+Bluebook+) to the gem root.
          # This file is loaded at boot time to reconstruct the domain IR without
          # requiring the original DSL source.
          #
          # @param root [String] absolute path to the gem root directory
          # @return [void]
          def generate_domain_rb(root)
            write_file(root, "#{bluebook_constant_name(@domain.name)}Bluebook", DslSerializer.new(@domain).serialize)
            copy_verbs_txt(root)
          end

          def copy_verbs_txt(root)
            return unless @domain.source_path
            src = File.join(File.dirname(@domain.source_path), "verbs.txt")
            FileUtils.cp(src, File.join(root, "verbs.txt")) if File.exist?(src)
          end

          # Injects autoload declarations into an aggregate class body, immediately
          # after the +class <AggName>+ line.
          #
          # @param code [String] the generated aggregate Ruby source
          # @param autoloads [String] the autoload lines to inject
          # @param agg_name [String] the PascalCase aggregate class name, used to
          #   locate the injection point
          # @return [String] the modified source with autoloads injected, or the
          #   original source unchanged if +autoloads+ is blank
          def inject_autoloads(code, autoloads, agg_name)
            return code if autoloads.strip.empty?
            marker = "class #{agg_name}\n"
            code.sub(marker, "#{marker}#{autoloads}\n\n")
          end

          # Writes a command file to disk, preserving any custom +call+ method
          # from an existing file. This prevents regeneration from overwriting
          # user-written business logic.
          #
          # Precedence:
          # 1. If the DSL defines a +call_body+, the generated code always wins
          # 2. If an existing file has a +call+ method that differs from the
          #    auto-generated one, the existing method is spliced into the new content
          # 3. Otherwise, the generated content is written as-is
          #
          # @param root [String] absolute path to the gem root directory
          # @param relative_path [String] path relative to +root+ for the command file
          # @param new_content [String] the freshly generated command Ruby source
          # @param command [Hecks::BluebookModel::Behavior::Command] the command IR,
          #   checked for +call_body+ to decide preservation behavior
          # @return [void]
          def write_command_file(root, relative_path, new_content, command)
            full_path = Hecks::Utils.safe_path!(root, relative_path)
            if !command.call_body && File.exist?(full_path)
              existing_source = File.read(full_path)
              existing_call = Hecks::Utils.extract_call_method(existing_source)
              generated_call = Hecks::Utils.extract_call_method(new_content)
              if existing_call && generated_call && existing_call.strip != generated_call.strip
                new_content = new_content.sub(generated_call, existing_call)
              end
            end
            write_file(root, relative_path, new_content)
          end

          # Writes content to a file, creating parent directories as needed.
          #
          # @param root [String] absolute path to the gem root directory
          # @param relative_path [String] path relative to +root+
          # @param content [String] the file content to write
          # @return [void]
          def write_file(root, relative_path, content)
            path = Hecks::Utils.safe_path!(root, relative_path)
            FileUtils.mkdir_p(File.dirname(path))
            File.write(path, content)
          end
        end
      end
    end
  end
end
