module Hecks
  module HTTP
    # Hecks::HTTP::JsonSchemaGenerator
    #
    # Generates a JSON Schema (2020-12) document from a domain definition.
    # HTTP layer — used alongside OpenapiGenerator to describe domain types.
    # Includes definitions for aggregates, value objects, commands, events,
    # and queries. Handles references, lists, and JSON attributes.
    #
    #   Hecks::HTTP::JsonSchemaGenerator.new(domain).generate
    #
    class JsonSchemaGenerator < Hecks::Generator
      # Creates a new JsonSchemaGenerator for a domain.
      #
      # @param domain [Hecks::BluebookModel::Structure::Domain] the parsed domain IR
      def initialize(domain)
        @domain = domain
      end

      # Generates a JSON Schema (2020-12) document describing all domain types.
      #
      # The returned hash includes:
      # - +$schema+ pointing to the JSON Schema 2020-12 meta-schema
      # - +title+ and +description+ metadata
      # - +definitions+ containing schemas for every aggregate, value object,
      #   entity, command, event, and query in the domain
      #
      # @return [Hash] a JSON Schema document as a Ruby hash (suitable for
      #   +JSON.generate+ or +to_json+)
      def generate
        {
          "$schema" => "https://json-schema.org/draft/2020-12/schema",
          title: "#{@domain.name} Domain Schema",
          description: "Generated by Hecks",
          definitions: build_definitions
        }
      end

      private

      # Builds the +definitions+ hash containing schemas for all domain types.
      # Iterates over every aggregate and its children (value objects, entities,
      # commands, events, queries).
      #
      # @return [Hash] a map of definition names to JSON Schema objects
      def build_definitions
        defs = {}
        @domain.aggregates.each do |agg|
          defs[agg.name] = aggregate_def(agg)
          agg.value_objects.each { |vo| defs["#{agg.name}::#{vo.name}"] = value_object_def(vo) }
          agg.entities.each { |ent| defs["#{agg.name}::#{ent.name}"] = entity_def(ent) }
          agg.commands.each { |cmd| defs[cmd.name] = command_def(cmd) }
          agg.events.each { |evt| defs[evt.name] = event_def(evt) }
          agg.queries.each { |q| defs["#{agg.name}.#{bluebook_snake_name(q.name)}"] = query_def(agg, q) }
        end
        defs
      end

      # Builds a JSON Schema object definition for an aggregate, including +id+,
      # all declared attributes, +created_at+, and +updated_at+. List attributes
      # are rendered as arrays with +$ref+ items when the target type is a known
      # value object or entity.
      #
      # @param agg [Hecks::BluebookModel::Structure::Aggregate] the aggregate
      # @return [Hash] JSON Schema object definition
      def aggregate_def(agg)
        props = { id: { type: "string", format: "uuid" } }
        required = ["id"]
        agg.attributes.each do |attr|
          if attr.list?
            vo = agg.value_objects.find { |v| v.name == attr.type.to_s }
            ent = agg.entities.find { |e| e.name == attr.type.to_s } unless vo
            child = vo || ent
            props[attr.name] = { type: "array", items: child ? { "$ref" => "#/definitions/#{agg.name}::#{child.name}" } : { type: "object" } }
          else
            props[attr.name] = property(attr)
          end
        end
        (agg.references || []).each do |ref|
          props[ref.name] = { type: "string", format: "uuid", description: "Reference to #{ref.type}" }
        end
        props[:created_at] = { type: "string", format: "date-time" }
        props[:updated_at] = { type: "string", format: "date-time" }
        { type: "object", properties: props, required: required }
      end

      # Builds a JSON Schema object definition for a value object.
      #
      # @param vo [Hecks::BluebookModel::Structure::ValueObject] the value object
      # @return [Hash] JSON Schema object definition
      def value_object_def(vo)
        props = {}
        vo.attributes.each { |attr| props[attr.name] = property(attr) }
        { type: "object", properties: props }
      end

      # Builds a JSON Schema object definition for an entity, including a
      # required +id+ field.
      #
      # @param ent [Hecks::BluebookModel::Structure::Entity] the entity
      # @return [Hash] JSON Schema object definition with +id+ in +required+
      def entity_def(ent)
        props = { id: { type: "string", format: "uuid" } }
        ent.attributes.each { |attr| props[attr.name] = property(attr) }
        { type: "object", properties: props, required: ["id"] }
      end

      # Builds a JSON Schema object definition for a command. All attributes
      # are listed in +required+.
      #
      # @param cmd [Hecks::BluebookModel::Behavior::Command] the command
      # @return [Hash] JSON Schema object definition
      def command_def(cmd)
        props = {}
        required = []
        cmd.attributes.each do |attr|
          props[attr.name] = property(attr)
          required << attr.name.to_s
        end
        (cmd.references || []).each do |ref|
          props[ref.name] = { type: "string", format: "uuid", description: "Reference to #{ref.type}" }
          required << ref.name.to_s
        end
        { type: "object", properties: props, required: required }
      end

      # Builds a JSON Schema object definition for an event, including an
      # +occurred_at+ timestamp field.
      #
      # @param evt [Hecks::BluebookModel::Behavior::Event] the event
      # @return [Hash] JSON Schema object definition
      def event_def(evt)
        props = { occurred_at: { type: "string", format: "date-time" } }
        evt.attributes.each { |attr| props[attr.name] = property(attr) }
        { type: "object", properties: props }
      end

      # Builds a JSON Schema-like definition for a query, listing its parameters
      # and declaring that it returns an array of the owning aggregate.
      #
      # @param agg [Hecks::BluebookModel::Structure::Aggregate] the owning aggregate
      # @param query [Hecks::BluebookModel::Behavior::Query] the query
      # @return [Hash] a definition with +description+, +parameters+, and +returns+
      def query_def(agg, query)
        params = query.block.parameters
        {
          description: "Returns array of #{agg.name}",
          parameters: params.map { |_, n| { name: n.to_s, type: "string" } },
          returns: { type: "array", items: { "$ref" => "#/definitions/#{agg.name}" } }
        }
      end

      # Maps a single domain attribute to a JSON Schema property definition.
      #
      # - JSON attributes -> +type: ["object", "array"]+
      # - Reference attributes -> +type: "string", format: "uuid"+
      # - +Integer+ -> +type: "integer"+
      # - +Float+ -> +type: "number"+
      # - All others -> +type: "string"+
      #
      # @param attr [Hecks::BluebookModel::Structure::Attribute] the attribute
      # @return [Hash] a JSON Schema property definition
      def property(attr)
        if attr.json?
          { type: ["object", "array"] }
        else
          { type: HecksTemplating::TypeContract.json(attr.ruby_type) }
        end
      end
    end
  end
end
