Hecks::Chapters.load_aggregates(
  Hecks::Bluebook::GeneratorsParagraph,
  base_dir: File.expand_path("openapi_generator", __dir__)
)

module Hecks
  module HTTP
    # Hecks::HTTP::OpenapiGenerator
    #
    # Generates an OpenAPI 3.0 spec from a domain. Every aggregate gets
    # CRUD paths, every query gets a GET path. Types derived from DSL.
    #
    # Path building  -> OpenapiGenerator::PathBuilder
    # Schema building -> OpenapiGenerator::SchemaBuilder
    # Response helpers -> OpenapiGenerator::ResponseHelpers
    #
    class OpenapiGenerator
      include ResponseHelpers
      include SchemaBuilder
      include PathBuilder

      # Creates a new OpenapiGenerator for a domain.
      #
      # @param domain [Hecks::BluebookModel::Structure::Domain] the parsed domain IR
      def initialize(domain)
        @domain = domain
      end

      # Generates an OpenAPI 3.0.0 specification document from the domain.
      #
      # The returned hash includes:
      # - +openapi+ version string (+"3.0.0"+)
      # - +info+ with title, version, and description
      # - +paths+ built by +PathBuilder+ (CRUD + query + SSE events)
      # - +components.schemas+ built by +SchemaBuilder+
      #
      # @return [Hash] an OpenAPI spec as a Ruby hash (suitable for
      #   +JSON.generate+ or YAML serialization)
      def generate
        {
          openapi: "3.0.0",
          info: { title: "#{@domain.name} API", version: "1.0.0", description: "Generated by Hecks" },
          paths: build_paths,
          components: { schemas: build_schemas }
        }
      end
    end
  end
end
