module Hecks
  module HTTP
    # Hecks::HTTP::RpcDiscovery
    #
    # Generates a JSON-RPC discovery document listing all available methods
    # for a domain: commands, queries, and CRUD operations (find, all, count, delete)
    # per aggregate. Used by RpcServer to advertise its capabilities.
    #
    class RpcDiscovery < Hecks::Generator
      # Creates a new RpcDiscovery generator for a domain.
      #
      # @param domain [Hecks::BluebookModel::Structure::Domain] the parsed domain IR
      def initialize(domain)
        @domain = domain
      end

      # Generates a JSON-RPC discovery document listing all available methods.
      #
      # The returned hash includes:
      # - +name+ -- the domain name with "RPC" suffix
      # - +description+ -- generator attribution
      # - +methods+ -- an array of method descriptors, each with +name+,
      #   +description+, and +params+
      #
      # Methods are generated for:
      # - Every command on every aggregate (params from command attributes)
      # - Every query on every aggregate (params from query block parameters)
      # - Built-in CRUD operations per aggregate: +find+, +all+, +count+, +delete+
      #
      # @return [Hash] a discovery document as a Ruby hash
      def generate
        {
          name: "#{@domain.name} RPC",
          description: "Generated by Hecks",
          methods: build_methods
        }
      end

      private

      # Builds the array of method descriptors for all aggregates.
      # Each descriptor has +name+ (String), +description+ (String), and
      # +params+ (Array of Hashes with +name+ and +type+ keys).
      #
      # @return [Array<Hash>] method descriptor objects
      def build_methods
        methods = []
        @domain.aggregates.each do |agg|
          agg.commands.each do |cmd|
            methods << {
              name: cmd.name,
              description: "#{agg.name} action",
              params: cmd.attributes.map { |a| { name: a.name.to_s, type: a.ruby_type } } +
                       (cmd.references || []).map { |r| { name: r.name.to_s, type: "String" } }
            }
          end
          agg.queries.each do |query|
            qn = bluebook_snake_name(query.name)
            params = query.block.parameters.map { |_, n| { name: n.to_s, type: "string" } }
            methods << { name: "#{agg.name}.#{qn}", description: "#{agg.name} lookup", params: params }
          end
          methods << { name: "#{agg.name}.find", description: "Find #{agg.name} by ID", params: [{ name: "id", type: "string" }] }
          methods << { name: "#{agg.name}.all", description: "List all #{agg.name}s", params: [] }
          methods << { name: "#{agg.name}.count", description: "Count #{agg.name}s", params: [] }
          methods << { name: "#{agg.name}.delete", description: "Delete #{agg.name}", params: [{ name: "id", type: "string" }] }
        end
        methods
      end
    end
  end
end
