module Hecks
  module HTTP
    # Hecks::HTTP::TypescriptGenerator
    #
    # Generates TypeScript type definitions (.d.ts) from a domain IR.
    # Produces interfaces for aggregates, value objects, and entities;
    # types for command inputs and event payloads; enums for lifecycles;
    # and string union types for references.
    #
    # Uses TypeContract for consistent type mapping across all targets.
    #
    #   Hecks::HTTP::TypescriptGenerator.new(domain).generate
    #   # => "// Generated by Hecks — Pizzas domain types\n\nexport interface Pizza { ... }\n..."
    #
    class TypescriptGenerator < Hecks::Generator
      # Creates a new TypescriptGenerator for a domain.
      #
      # @param domain [Hecks::BluebookModel::Structure::Domain] the parsed domain IR
      def initialize(domain)
        @domain = domain
      end

      # Generates a complete .d.ts file as a string.
      #
      # @return [String] TypeScript type definitions
      def generate
        sections = [header]
        @domain.aggregates.each { |agg| sections.concat(aggregate_sections(agg)) }
        sections.join("\n\n") + "\n"
      end

      private

      def header
        "// Generated by Hecks \u2014 #{@domain.name} domain types\n// Do not edit manually"
      end

      # Builds all sections for a single aggregate.
      #
      # @param agg [Hecks::BluebookModel::Structure::Aggregate]
      # @return [Array<String>]
      def aggregate_sections(agg)
        parts = []
        agg.value_objects.each { |vo| parts << interface_block(vo.name, vo_fields(vo)) }
        agg.entities.each { |ent| parts << interface_block(ent.name, entity_fields(ent)) }
        parts << lifecycle_enum(agg) if agg.lifecycle
        parts << interface_block(agg.name, aggregate_fields(agg))
        agg.commands.each { |cmd| parts << type_block(cmd.name, command_fields(cmd)) }
        agg.events.each { |evt| parts << type_block(evt.name, event_fields(evt)) }
        parts
      end

      # Builds field lines for an aggregate interface.
      def aggregate_fields(agg)
        fields = [field("id", "string")]
        agg.attributes.each { |attr| fields << attribute_field(attr, agg) }
        (agg.references || []).each { |ref| fields << field(ref.name, "string", "Reference to #{ref.type}") }
        fields << field("createdAt", "string")
        fields << field("updatedAt", "string")
        fields
      end

      # Builds field lines for a value object interface.
      def vo_fields(vo)
        vo.attributes.map { |attr| attribute_field(attr) }
      end

      # Builds field lines for an entity interface.
      def entity_fields(ent)
        [field("id", "string")] + ent.attributes.map { |attr| attribute_field(attr) }
      end

      # Builds field lines for a command type.
      def command_fields(cmd)
        fields = cmd.attributes.map { |attr| attribute_field(attr) }
        (cmd.references || []).each { |ref| fields << field(ref.name, "string", "Reference to #{ref.type}") }
        fields
      end

      # Builds field lines for an event type.
      def event_fields(evt)
        fields = [field("occurredAt", "string")]
        evt.attributes.each { |attr| fields << attribute_field(attr) }
        (evt.references || []).each { |ref| fields << field(ref.name, "string", "Reference to #{ref.type}") }
        fields
      end

      # Converts a domain attribute to a TypeScript field string.
      def attribute_field(attr, agg = nil)
        ts_type = resolve_type(attr, agg)
        ts_type = "#{ts_type}[]" if attr.list?
        field(attr.name, ts_type)
      end

      # Resolves the TypeScript type for a domain attribute.
      def resolve_type(attr, agg = nil)
        return "Record<string, unknown>" if attr.json?
        return attr.enum.map { |v| "\"#{v}\"" }.join(" | ") if attr.respond_to?(:enum) && attr.enum

        if agg && child_type?(attr, agg)
          attr.type.to_s
        else
          HecksTemplating::TypeContract.typescript(normalize_type(attr.ruby_type))
        end
      end

      # Normalizes Ruby type names to TypeContract-recognized names.
      # TrueClass/FalseClass -> "Boolean" for correct mapping.
      def normalize_type(ruby_type)
        case ruby_type
        when "TrueClass", "FalseClass" then "Boolean"
        else ruby_type
        end
      end

      # Checks if an attribute's type is a child value object or entity.
      def child_type?(attr, agg)
        agg.value_objects.any? { |vo| vo.name == attr.type.to_s } ||
          agg.entities.any? { |ent| ent.name == attr.type.to_s }
      end

      # Generates an enum for lifecycle states.
      def lifecycle_enum(agg)
        states = agg.lifecycle.states.map { |s| "  #{camel_case(s)} = \"#{s}\"" }
        "export enum #{agg.name}Status {\n#{states.join(",\n")}\n}"
      end

      # Formats a single field line.
      def field(name, type, comment = nil)
        line = "  #{camel_case_field(name)}: #{type};"
        line += " // #{comment}" if comment
        line
      end

      # Builds an interface block string.
      def interface_block(name, fields)
        "export interface #{name} {\n#{fields.join("\n")}\n}"
      end

      # Builds a type block string (identical syntax but uses `type`).
      def type_block(name, fields)
        "export type #{name} = {\n#{fields.join("\n")}\n};"
      end

      # Converts a snake_case or Symbol name to camelCase for TypeScript.
      def camel_case_field(name)
        parts = name.to_s.split("_")
        parts[0] + parts[1..].map(&:capitalize).join
      end

      # Converts a string to PascalCase for enum members.
      def camel_case(str)
        str.to_s.split(/[_\s]/).map(&:capitalize).join
      end
    end
  end
end
