# frozen_string_literal: true
#
# SnapshotWriter — renders the top-N tool roster as markdown, grouped by
# MCP server, with one-line descriptions when known. The rendered markdown
# is the surface the UserPromptSubmit hook injects as additionalContext at
# session start.
#
# Group derivation rule : an MCP tool name has the form
# "mcp__<server>__<server>__<verb>" ; we extract the first server segment
# as the group. Non-MCP harness tools (Bash / Edit / Read / Voice / etc.)
# group under "native".
#
# Usage :
#
#   md = SnapshotWriter.render(stats, top_n: 40)
#   File.write('/tmp/tool_cache_latest.md', md)
#
# `stats` is the hash TranscriptWalker.walk returns (sorted by count desc).

module SnapshotWriter
  module_function

  # Render the top-N entries from `stats` as a markdown catalog.
  # `stats` is { name => { count:, last_seen:, description: } }.
  def render(stats, top_n: 40)
    top = stats.first(top_n)
    grouped = group_by_server(top)
    sections = grouped.map { |server, tools| render_section(server, tools) }

    <<~MD
      # MCP tool-cache — top #{top.size} of #{stats.size} observed tools

      _Auto-generated by `bin/update-tool-cache` at session start. The catalog
      below is the discoverable surface : if a tool is listed here, it is
      callable via its verbatim name (Layer 1 of i654). Tools NOT in this list
      may still exist — use `ToolSearch` or `bin/storehouse-tools` to find
      them (Layer 2)._

      #{sections.join("\n")}
    MD
  end

  # Group the top-N tool list by MCP server. Returns a Hash preserving
  # insertion order (most-called server first).
  def group_by_server(top)
    grouped = {}
    top.each do |name, info|
      server = server_of(name)
      grouped[server] ||= []
      grouped[server] << [name, info]
    end
    grouped
  end

  # Extract the MCP server segment from a tool name. Returns 'native' for
  # harness tools, plugin-prefix-stripped names for plugin servers, and
  # the raw server segment otherwise.
  def server_of(name)
    return 'native' unless name.start_with?('mcp__')

    parts = name.split('__')
    return 'native' if parts.size < 3

    # plugin-namespaced servers look like mcp__plugin_<plugin>_<server>__...
    # we want a readable group name : just the <server> part.
    server = parts[1]
    server.sub(/^plugin_[^_]+_/, '')
  end

  # Render one server-grouped section.
  def render_section(server, tools)
    lines = ["## #{server} (#{tools.size})"]
    tools.each do |name, info|
      lines << render_tool_line(name, info)
    end
    lines.join("\n")
  end

  # One markdown line per tool : `- **name** — N calls — description`.
  def render_tool_line(name, info)
    desc = info[:description].to_s.strip
    desc = desc.empty? ? '(no description cached)' : desc
    "- **#{name}** — #{info[:count]} calls — #{desc}"
  end
end
