require "fileutils"

# NodeHecks::ProjectGenerator
#
# Generates a complete Node.js/TypeScript project from a domain IR.
# Produces TypeScript interfaces, command functions, in-memory repositories,
# an Express server, package.json, tsconfig.json, and a README.
#
#   gen = ProjectGenerator.new(domain, output_dir: "examples")
#   gen.generate  # => path to generated Node project
#
module NodeHecks
  class ProjectGenerator
    include NodeUtils

    def initialize(domain, output_dir: ".")
      @domain = domain
      @output_dir = output_dir
    end

    def generate
      name = NodeUtils.snake_case(@domain.name)
      @root = File.join(@output_dir, "#{name}_static_node")
      FileUtils.mkdir_p(@root)

      generate_aggregates
      generate_commands
      generate_repositories
      generate_server
      generate_package_json
      generate_tsconfig
      generate_readme
      # TODO: Generate service stubs from @domain.services (HEC-32)

      @root
    end

    private

    def write(path, content)
      full = File.join(@root, path)
      FileUtils.mkdir_p(File.dirname(full))
      File.write(full, content)
    end

    def generate_aggregates
      @domain.aggregates.each do |agg|
        gen = AggregateGenerator.new(agg)
        write("src/aggregates/#{NodeUtils.snake_case(agg.name)}.ts", gen.generate)
      end
    end

    def generate_commands
      @domain.aggregates.each do |agg|
        agg.commands.each_with_index do |cmd, i|
          event = agg.events[i]
          gen = CommandGenerator.new(cmd, aggregate: agg, event: event)
          write("src/commands/#{NodeUtils.snake_case(cmd.name)}.ts", gen.generate)
        end
      end
    end

    def generate_repositories
      @domain.aggregates.each do |agg|
        gen = RepositoryGenerator.new(agg)
        write("src/repositories/#{NodeUtils.snake_case(agg.name)}_repository.ts", gen.generate)
      end
    end

    def generate_server
      gen = ServerGenerator.new(@domain)
      write("src/server.ts", gen.generate)
    end

    def generate_package_json
      name = NodeUtils.kebab_case(@domain.name)
      write("package.json", <<~JSON)
        {
          "name": "#{name}-domain",
          "version": "1.0.0",
          "type": "module",
          "scripts": {
            "dev": "ts-node --esm src/server.ts",
            "build": "tsc",
            "start": "node dist/server.js"
          },
          "dependencies": {
            "express": "^4.21.0"
          },
          "devDependencies": {
            "@types/express": "^5.0.0",
            "@types/node": "^22.0.0",
            "typescript": "^5.7.0",
            "ts-node": "^10.9.0"
          }
        }
      JSON
    end

    def generate_tsconfig
      write("tsconfig.json", <<~JSON)
        {
          "compilerOptions": {
            "target": "ES2022",
            "module": "ESNext",
            "moduleResolution": "node",
            "strict": true,
            "esModuleInterop": true,
            "outDir": "dist",
            "rootDir": "src",
            "declaration": true
          },
          "include": ["src/**/*"]
        }
      JSON
    end

    def generate_readme
      name = @domain.name
      write("README.md", <<~MD)
        # #{name} Domain (Node.js/TypeScript)

        Generated by `hecks build --target node`.

        ## Getting started

        ```bash
        npm install
        npm run dev
        ```

        ## API

        #{@domain.aggregates.map { |a| "- `GET /#{NodeUtils.snake_case(a.name)}s` — list all #{a.name} records\n- `GET /#{NodeUtils.snake_case(a.name)}s/:id` — find #{a.name} by ID" }.join("\n")}
      MD
    end
  end
end
