  # Hecks::Specification
  #
  # Base mixin that generated specification classes include. Specifications are
  # reusable, composable predicate objects that encapsulate business rules.
  # Supports boolean composition via and/or/not operators.
  #
  # Part of the domain behavior layer. Generated by SpecificationGenerator and
  # included in specification classes within the domain gem.
  #
  # == Composition
  #
  # Specifications can be combined using boolean operators:
  # - +spec.and(other)+ -- both must be satisfied (returns +AndSpecification+)
  # - +spec.or(other)+ -- at least one must be satisfied (returns +OrSpecification+)
  # - +spec.not+ -- negates the specification (returns +NotSpecification+)
  #
  # Composite specifications are themselves specifications and can be further
  # composed, forming an expression tree.
  #
  # == Usage
  #
  #   class HighRisk
  #     include Hecks::Specification
  #
  #     def satisfied_by?(loan)
  #       loan.principal > 50_000 && loan.rate > 10
  #     end
  #   end
  #
  #   spec = HighRisk.new
  #   spec.satisfied_by?(loan)           # => true/false
  #   combo = spec.and(AnotherSpec.new)   # => AndSpecification
  #   combo.satisfied_by?(loan)           # => true/false
  #
  #   # Class-level shortcut (no need to instantiate):
  #   HighRisk.satisfied_by?(loan)        # => true/false
  #
module Hecks
  # Hecks::Specification
  #
  # Base mixin for specification classes providing composable business rule predicates with and/or/not operators.
  #
  module Specification
    # Hook called when a class includes +Hecks::Specification+. Extends the
    # class with a class-level +satisfied_by?+ convenience method.
    #
    # @param base [Class] the class including this module
    # @return [void]
    def self.included(base)
      base.extend(ClassMethods)
    end

    # Class-level convenience methods for specification classes.
    module ClassMethods
      # Class-level convenience that creates an instance and checks the predicate.
      # Useful when the specification has no constructor arguments.
      #
      # @param object [Object] the domain object to test
      # @return [Boolean] whether the object satisfies this specification
      def satisfied_by?(object)
        new.satisfied_by?(object)
      end
    end

    # Returns whether the given object satisfies this specification.
    # Subclasses must override this method with their business rule logic.
    #
    # @param _object [Object] the domain object to test
    # @return [Boolean] whether the object satisfies this specification
    # @raise [NotImplementedError] if the subclass has not implemented this method
    def satisfied_by?(_object)
      raise NotImplementedError, "#{self.class}#satisfied_by? must be implemented"
    end

    # Returns a composite specification requiring both this and +other+ to be satisfied.
    #
    # @param other [#satisfied_by?] another specification to combine with
    # @return [AndSpecification] a composite specification (logical AND)
    def and(other)
      AndSpecification.new(self, other)
    end

    # Returns a composite specification requiring either this or +other+ to be satisfied.
    #
    # @param other [#satisfied_by?] another specification to combine with
    # @return [OrSpecification] a composite specification (logical OR)
    def or(other)
      OrSpecification.new(self, other)
    end

    # Returns a specification that negates this one.
    #
    # @return [NotSpecification] a specification that returns the opposite of this one
    def not
      NotSpecification.new(self)
    end

    # Composite specification that requires both wrapped specifications to be satisfied.
    # Created via +spec.and(other)+; can itself be further composed.
    class AndSpecification
      include Specification

      # @param left [#satisfied_by?] the first specification
      # @param right [#satisfied_by?] the second specification
      def initialize(left, right)
        @left = left
        @right = right
      end

      # Returns true only if both wrapped specifications are satisfied.
      #
      # @param object [Object] the domain object to test
      # @return [Boolean]
      def satisfied_by?(object)
        @left.satisfied_by?(object) && @right.satisfied_by?(object)
      end
    end

    # Composite specification that requires at least one wrapped specification to be satisfied.
    # Created via +spec.or(other)+; can itself be further composed.
    class OrSpecification
      include Specification

      # @param left [#satisfied_by?] the first specification
      # @param right [#satisfied_by?] the second specification
      def initialize(left, right)
        @left = left
        @right = right
      end

      # Returns true if at least one wrapped specification is satisfied.
      #
      # @param object [Object] the domain object to test
      # @return [Boolean]
      def satisfied_by?(object)
        @left.satisfied_by?(object) || @right.satisfied_by?(object)
      end
    end

    # Composite specification that negates the wrapped specification.
    # Created via +spec.not+; can itself be further composed.
    class NotSpecification
      include Specification

      # @param spec [#satisfied_by?] the specification to negate
      def initialize(spec)
        @spec = spec
      end

      # Returns true if the wrapped specification is NOT satisfied.
      #
      # @param object [Object] the domain object to test
      # @return [Boolean]
      def satisfied_by?(object)
        !@spec.satisfied_by?(object)
      end
    end
  end
end
