//! Cloudflare-Pages Function proxy emitter — i528 step 9, the third
//! member of the `:codegen` adapter family declared in
//! command_bus.hecksagon.
//!
//! [antibody-exempt: rust/src/specializer/cf_function_proxy.rs —
//!  kernel-floor codegen emitter. Reads a project's (app,
//!  worker_url_env, auth_secret_env, allow_methods) tuple and emits
//!  one Pages-Function JS file — a catch-all under
//!  <app>/functions/api/[[route]].js that forwards any /api/* call
//!  to the deployed WASM Worker with the bearer secret. Sibling to
//!  wasm_worker (the Worker the proxy targets) and ruby_command_class
//!  (Ruby call-site emitter for the same bus). Shape declared in
//!  codegen/cf_function_proxy_shape/. Retires under i78 once the
//!  codegen meta-shape itself becomes bluebook-generated.]
//!
//! The emitted JS is small — ~70 lines that parse params.route into
//! a path, forward method + headers (minus host) + body to the
//! worker URL with `Authorization: Bearer ${env[auth_secret_env]}`,
//! and return the worker's response unchanged. Disallowed methods
//! return 405 ; missing env vars at runtime return 500 with a JSON
//! error body.

/// Render the catch-all Pages Function JS as a string.
///
/// `app` is the kebab-case project folder. `worker_url_env` and
/// `auth_secret_env` are env-var names the JS reads at runtime via
/// `env[...]`. `allow_methods` is a JSON-array string like
/// `["GET","POST"]`.
pub fn emit_proxy(
    app: &str,
    worker_url_env: &str,
    auth_secret_env: &str,
    allow_methods: &str,
    auth_mode: &str,
) -> String {
    // auth_mode = "inject" (default, current behaviour : the proxy
    // injects the bearer for every caller — correct for a public
    // form like EarlyAccess) | "enforce" (owner-only buses, e.g. a
    // CMS : the caller MUST present the bearer on writes, else 401).
    // Empty string in inject mode keeps the emitted JS byte-identical
    // to the pre-auth_mode output, so bin-buddy / mietteai are
    // unaffected and existing goldens/tests stay green.
    let gate = if auth_mode == "enforce" {
        format!(
            "{ind}// Owner-auth gate (auth_mode=enforce). Writes MUST present\n\
             {ind}// Authorization: Bearer <secret> matching the env-bound\n\
             {ind}// bearer, else 401. GET (read-only) stays open. The\n\
             {ind}// generator default is inject (public-form pattern) ;\n\
             {ind}// owner-only buses pass --auth-mode enforce.\n\
             {ind}if (request.method !== 'GET') {{\n\
             {ind}{ind}const got = (request.headers.get('Authorization') || '').replace(/^Bearer\\s+/i, '');\n\
             {ind}{ind}if (got.length !== bearer.length || got !== bearer) {{\n\
             {ind}{ind}{ind}return new Response(\n\
             {ind}{ind}{ind}{ind}JSON.stringify({{ service: '{app}-proxy', error: 'unauthorized' }}),\n\
             {ind}{ind}{ind}{ind}{{ status: 401, headers: {{ 'content-type': 'application/json' }} }},\n\
             {ind}{ind}{ind});\n\
             {ind}{ind}}}\n\
             {ind}}}\n\
             \n\
             ",
            ind = "  ",
            app = app,
        )
    } else {
        String::new()
    };
    format!(
        "// AUTO-GENERATED by storehouse — do not edit by hand.\n\
         // Source : {app} world file ; regenerate with `storehouse specialize cf_function_proxy --app {app}`.\n\
         //\n\
         // Cloudflare-Pages Function — catch-all proxy under /api/*.\n\
         //\n\
         // Forwards any GET / POST under /api/* to the deployed WASM Worker\n\
         // (i528 step 8 ; same app, same bus). The Worker URL is read from\n\
         // env.{worker_url_env} at request time ; the bearer secret from\n\
         // env.{auth_secret_env}. Both are set via\n\
         // `wrangler pages secret put <name> --project-name={app}`.\n\
         //\n\
         // Bridge between the portal layer (browser, static assets) and the\n\
         // CommandBus layer (WASM Worker, the bus itself). The portal calls\n\
         //   fetch('/api/route', {{ method: 'POST', body: ... }})\n\
         // and this Function relays the call to\n\
         //   {{worker_url}}/route\n\
         // with the Authorization header set. Response body is returned\n\
         // unchanged so portal code sees what the Worker said.\n\
         \n\
         const ALLOWED_METHODS = new Set({allow_methods});\n\
         \n\
         export async function onRequest(context) {{\n\
         {ind}const {{ request, env, params }} = context;\n\
         \n\
         {ind}// Resolve the upstream URL from the worker-URL env var.\n\
         {ind}const workerUrl = env.{worker_url_env};\n\
         {ind}const bearer    = env.{auth_secret_env};\n\
         {ind}if (!workerUrl || !bearer) {{\n\
         {ind}{ind}return new Response(\n\
         {ind}{ind}{ind}JSON.stringify({{\n\
         {ind}{ind}{ind}{ind}service: '{app}-proxy',\n\
         {ind}{ind}{ind}{ind}error:   'missing env',\n\
         {ind}{ind}{ind}{ind}detail:  'one or more of {worker_url_env}, {auth_secret_env} not bound on this Pages deployment',\n\
         {ind}{ind}{ind}}}),\n\
         {ind}{ind}{ind}{{ status: 500, headers: {{ 'content-type': 'application/json' }} }},\n\
         {ind}{ind});\n\
         {ind}}}\n\
         \n\
         {ind}// Catch-all : Cloudflare populates params.route with the\n\
         {ind}// portion of the path after /api/. \"/api/route\" → [\"route\"],\n\
         {ind}// \"/api/lexicon\" → [\"lexicon\"]. Join with `/` and prefix.\n\
         {ind}const tail = Array.isArray(params.route) ? params.route.join('/') : (params.route || '');\n\
         {ind}const upstream = workerUrl.replace(/\\/+$/, '') + '/' + tail;\n\
         \n\
         {ind}// Method gate — only forward methods the bus surface declares.\n\
         {ind}if (!ALLOWED_METHODS.has(request.method)) {{\n\
         {ind}{ind}return new Response('Method Not Allowed', {{\n\
         {ind}{ind}{ind}status: 405,\n\
         {ind}{ind}{ind}headers: {{ 'allow': [...ALLOWED_METHODS].join(', ') }},\n\
         {ind}{ind}}});\n\
         {ind}}}\n\
         \n\
         {gate}{ind}// Build the upstream request. Headers carry over except for\n\
         {ind}// host (the upstream is a different origin) ; Authorization\n\
         {ind}// is set fresh from the env-bound bearer secret.\n\
         {ind}const headers = new Headers();\n\
         {ind}for (const [k, v] of request.headers.entries()) {{\n\
         {ind}{ind}if (k.toLowerCase() === 'host') continue;\n\
         {ind}{ind}headers.set(k, v);\n\
         {ind}}}\n\
         {ind}headers.set('Authorization', 'Bearer ' + bearer);\n\
         \n\
         {ind}const init = {{\n\
         {ind}{ind}method:  request.method,\n\
         {ind}{ind}headers: headers,\n\
         {ind}{ind}body:    request.method === 'GET' ? undefined : await request.arrayBuffer(),\n\
         {ind}}};\n\
         \n\
         {ind}try {{\n\
         {ind}{ind}const upstreamResponse = await fetch(upstream, init);\n\
         {ind}{ind}return upstreamResponse;\n\
         {ind}}} catch (err) {{\n\
         {ind}{ind}return new Response(\n\
         {ind}{ind}{ind}JSON.stringify({{\n\
         {ind}{ind}{ind}{ind}service: '{app}-proxy',\n\
         {ind}{ind}{ind}{ind}error:   'upstream fetch failed',\n\
         {ind}{ind}{ind}{ind}detail:  String(err && err.message ? err.message : err),\n\
         {ind}{ind}{ind}}}),\n\
         {ind}{ind}{ind}{{ status: 502, headers: {{ 'content-type': 'application/json' }} }},\n\
         {ind}{ind});\n\
         {ind}}}\n\
         }}\n",
        app = app,
        worker_url_env = worker_url_env,
        auth_secret_env = auth_secret_env,
        allow_methods = allow_methods,
        gate = gate,
        ind = "  ",
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn proxy_header_carries_app_name() {
        let js = emit_proxy(
            "bin-buddy",
            "BIN_BUDDY_WORKER_URL",
            "BIN_BUDDY_API_KEY",
            "[\"GET\",\"POST\"]",
            "inject",
        );
        assert!(js.contains("Source : bin-buddy world file"));
        assert!(js.contains("service: 'bin-buddy-proxy'"));
    }

    #[test]
    fn proxy_reads_named_env_vars_at_runtime() {
        let js = emit_proxy(
            "bin-buddy",
            "BIN_BUDDY_WORKER_URL",
            "BIN_BUDDY_API_KEY",
            "[\"GET\",\"POST\"]",
            "inject",
        );
        assert!(js.contains("env.BIN_BUDDY_WORKER_URL"));
        assert!(js.contains("env.BIN_BUDDY_API_KEY"));
    }

    #[test]
    fn proxy_builds_upstream_url_from_route_param() {
        let js = emit_proxy(
            "bin-buddy",
            "BIN_BUDDY_WORKER_URL",
            "BIN_BUDDY_API_KEY",
            "[\"GET\",\"POST\"]",
            "inject",
        );
        // Catch-all path : params.route is the rest of /api/*.
        assert!(js.contains("params.route"));
        assert!(js.contains("workerUrl.replace(/\\/+$/, '') + '/' + tail"));
    }

    #[test]
    fn proxy_gates_methods_with_405() {
        let js = emit_proxy(
            "bin-buddy",
            "BIN_BUDDY_WORKER_URL",
            "BIN_BUDDY_API_KEY",
            "[\"GET\",\"POST\"]",
            "inject",
        );
        assert!(js.contains("ALLOWED_METHODS"));
        assert!(js.contains("status: 405"));
    }

    #[test]
    fn proxy_sets_bearer_authorization_from_env() {
        let js = emit_proxy(
            "bin-buddy",
            "BIN_BUDDY_WORKER_URL",
            "BIN_BUDDY_API_KEY",
            "[\"GET\",\"POST\"]",
            "inject",
        );
        assert!(js.contains("headers.set('Authorization', 'Bearer ' + bearer)"));
    }

    #[test]
    fn enforce_mode_gates_writes_inject_does_not() {
        let inj = emit_proxy("cms", "CMS_WORKER_URL", "CMS_OWNER_TOKEN", "[\"GET\",\"POST\"]", "inject");
        let enf = emit_proxy("cms", "CMS_WORKER_URL", "CMS_OWNER_TOKEN", "[\"GET\",\"POST\"]", "enforce");
        assert!(!inj.contains("error: 'unauthorized'"), "inject must not gate callers");
        assert!(enf.contains("status: 401"), "enforce must 401 unauthenticated writes");
        assert!(enf.contains("request.method !== 'GET'"), "enforce gates non-GET only");
        assert!(enf.contains("error: 'unauthorized'"));
        // Both still inject the upstream bearer (the Worker double-checks).
        assert!(inj.contains("headers.set('Authorization', 'Bearer ' + bearer)"));
        assert!(enf.contains("headers.set('Authorization', 'Bearer ' + bearer)"));
    }

    #[test]
    fn proxy_handles_missing_env_with_500() {
        let js = emit_proxy(
            "bin-buddy",
            "BIN_BUDDY_WORKER_URL",
            "BIN_BUDDY_API_KEY",
            "[\"GET\",\"POST\"]",
            "inject",
        );
        assert!(js.contains("'missing env'"));
        assert!(js.contains("status: 500"));
    }

    #[test]
    fn dump_bin_buddy_smoke_to_tmp() {
        let js = emit_proxy(
            "bin-buddy",
            "BIN_BUDDY_WORKER_URL",
            "BIN_BUDDY_API_KEY",
            "[\"GET\",\"POST\"]",
            "inject",
        );
        let _ = std::fs::write("/tmp/bin_buddy_proxy_route.js", &js);
    }
}
