//! Ruby command-class emitter — i528 step 7, the first member of the
//! `:codegen` adapter family declared in command_bus.hecksagon.
//!
//! [antibody-exempt: rust/src/specializer/ruby_command_class.rs —
//!  kernel-floor codegen emitter. Reads a bluebook IR Domain and
//!  produces idiomatic Ruby source : one class per command, kwarg
//!  initializer, .call delegates to Storehouse.route with the
//!  canonical four-segment phrase from i528. Shape declared in
//!  codegen/ruby_command_class_shape/. Retires under the broader
//!  i78 (specializer-files-as-bluebook) once the codegen meta-shape
//!  itself becomes bluebook-generated.]
//!
//! Given a parsed bluebook Domain + the (app, domain) prefix derived
//! from the bluebook's filesystem location, this emits one Ruby file
//! with one module-nested class per command :
//!
//! ```text
//! module App
//!   module Domain
//!     class CommandName
//!       def initialize(kwarg1:, kwarg2:, ...)
//!         @kwarg1 = kwarg1
//!         @kwarg2 = kwarg2
//!       end
//!
//!       def call
//!         Storehouse.route(
//!           "app::domain::Aggregate::CommandName",
//!           kwarg1: @kwarg1,
//!           kwarg2: @kwarg2,
//!         )
//!       end
//!     end
//!   end
//! end
//! ```
//!
//! Ruby module-naming convention : `app` (kebab) → PascalCase
//! (e.g. `bin-buddy` → `BinBuddy`) ; `domain` likewise. Command
//! names stay PascalCase end-to-end. The four-segment phrase
//! itself uses the raw `app`/`domain` strings (kebab) to match
//! the bus's expectation.

use crate::ir::Domain;

/// Render the full Ruby file for one bluebook : one class per
/// command across all aggregates in the Domain, all nested under
/// `module App::Domain`.
///
/// `app` is the kebab-case project folder name (e.g. "bin-buddy").
/// `domain` is the kebab-case sub-folder name (e.g. "notifications").
pub fn emit_from_domain(domain: &Domain, app: &str, domain_name: &str) -> String {
    let app_module = kebab_to_pascal(app);
    let domain_module = snake_or_kebab_to_pascal(domain_name);

    let mut out = String::new();

    // File header
    out.push_str(&format!(
        "# Generated by storehouse — do not edit by hand.\n\
         # Source : {} bluebook (app: {}, domain: {})\n\
         #\n\
         # Each class below is a Ruby idiom over a four-segment bus phrase.\n\
         # Calling `.new(**params).call` lands on the same bus that the HTTP\n\
         # API + CLI + WASM realizations route through (Storehouse.route).\n\n\
         require \"storehouse\"\n\n",
        domain.name, app, domain_name,
    ));

    out.push_str(&format!("module {}\n", app_module));
    out.push_str(&format!("  module {}\n", domain_module));

    let mut first_class = true;
    for agg in &domain.aggregates {
        for cmd in &agg.commands {
            if !first_class {
                out.push('\n');
            }
            first_class = false;

            let phrase = format!(
                "{}::{}::{}::{}",
                app, domain_name, agg.name, cmd.name
            );

            // Collect command attribute names (snake_case as declared).
            let attrs: Vec<&str> = cmd
                .attributes
                .iter()
                .map(|a| a.name.as_str())
                .collect();

            // Class header
            out.push_str(&format!("    class {}\n", cmd.name));

            // initialize
            if attrs.is_empty() {
                out.push_str("      def initialize\n      end\n\n");
            } else {
                out.push_str("      def initialize(");
                out.push_str(
                    &attrs
                        .iter()
                        .map(|n| format!("{}:", n))
                        .collect::<Vec<_>>()
                        .join(", "),
                );
                out.push_str(")\n");
                for a in &attrs {
                    out.push_str(&format!("        @{} = {}\n", a, a));
                }
                out.push_str("      end\n\n");
            }

            // call
            out.push_str("      def call\n");
            if attrs.is_empty() {
                out.push_str(&format!(
                    "        Storehouse.route(\"{}\")\n",
                    phrase
                ));
            } else {
                out.push_str(&format!(
                    "        Storehouse.route(\n          \"{}\",\n",
                    phrase
                ));
                for a in &attrs {
                    out.push_str(&format!("          {}: @{},\n", a, a));
                }
                out.push_str("        )\n");
            }
            out.push_str("      end\n");
            out.push_str("    end\n");
        }
    }

    out.push_str("  end\n");
    out.push_str("end\n");

    out
}

/// Convert kebab-case ("bin-buddy") to PascalCase ("BinBuddy").
fn kebab_to_pascal(s: &str) -> String {
    s.split('-')
        .map(capitalize)
        .collect::<Vec<_>>()
        .join("")
}

/// Convert snake_case or kebab-case ("my_thing" / "my-thing") to
/// PascalCase ("MyThing"). Both separators handled.
fn snake_or_kebab_to_pascal(s: &str) -> String {
    s.split(|c: char| c == '_' || c == '-')
        .map(capitalize)
        .collect::<Vec<_>>()
        .join("")
}

fn capitalize(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        Some(c) => c.to_uppercase().collect::<String>() + chars.as_str(),
        None => String::new(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parser;

    #[test]
    fn emits_module_nested_classes_for_each_command() {
        // Minimal bluebook with one aggregate and two commands.
        let source = r#"
Hecks.bluebook "Hello", version: "2026.05.11.1" do
  vision "test fixture"

  aggregate "Greeter", "Says hello" do
    identified_by :name

    value_object "Name" do
      attribute :value, String
    end

    attribute :name, Name

    command "Greet" do
      role "User"
      attribute :name, Name
      emits "Greeted"
      then_set :name, to: :name
    end

    command "WaveGoodbye" do
      role "User"
      emits "Waved"
    end
  end
end
"#;
        let domain = parser::parse(source);
        let ruby = emit_from_domain(&domain, "bin-buddy", "greeting");

        // Module nesting carries the app + domain.
        assert!(ruby.contains("module BinBuddy"));
        assert!(ruby.contains("  module Greeting"));

        // One class per command.
        assert!(ruby.contains("    class Greet"));
        assert!(ruby.contains("    class WaveGoodbye"));

        // initialize takes the command's attributes as kwargs.
        assert!(ruby.contains("def initialize(name:)"));
        assert!(ruby.contains("@name = name"));

        // No-attribute command gets a bare initialize.
        assert!(ruby.contains("class WaveGoodbye\n      def initialize\n      end"));

        // .call dispatches through Storehouse.route with the
        // canonical four-segment phrase.
        assert!(ruby.contains(
            r#"Storehouse.route(
          "bin-buddy::greeting::Greeter::Greet","#
        ));

        // No-attribute command's call is the single-arg form.
        assert!(ruby.contains(
            r#"Storehouse.route("bin-buddy::greeting::Greeter::WaveGoodbye")"#
        ));
    }

    #[test]
    fn kebab_to_pascal_round_trips() {
        assert_eq!(kebab_to_pascal("bin-buddy"), "BinBuddy");
        assert_eq!(kebab_to_pascal("hecks-conception"), "HecksConception");
        assert_eq!(kebab_to_pascal("simple"), "Simple");
    }

    #[test]
    fn snake_or_kebab_handles_both_separators() {
        assert_eq!(snake_or_kebab_to_pascal("my_thing"), "MyThing");
        assert_eq!(snake_or_kebab_to_pascal("my-thing"), "MyThing");
        assert_eq!(snake_or_kebab_to_pascal("notifications"), "Notifications");
    }
}
