//! WASM Cloudflare-Worker emitter — i528 step 8, the second member
//! of the `:codegen` adapter family declared in command_bus.hecksagon.
//!
//! [antibody-exempt: rust/src/specializer/wasm_worker.rs — kernel-floor
//!  codegen emitter. Reads a project's (app, host, auth_scheme,
//!  auth_secret_env, storehouse_path) tuple from its world file and
//!  emits two strings : the worker's Cargo.toml (workspace member,
//!  cdylib, path-dep on storehouse, release profile tuned for the
//!  1MB CF Worker limit) and src/lib.rs (the workers-rs fetch
//!  handler routed to the four endpoints the CommandBus bluebook
//!  declares). Shape declared in codegen/wasm_worker_shape/. Retires
//!  under the broader i78 (specializer-files-as-bluebook) once the
//!  codegen meta-shape itself becomes bluebook-generated.]
//!
//! Sibling to `ruby_command_class` — same `:codegen` adapter family,
//! different target language (Rust → WASM instead of Ruby). The two
//! emitters share the same input convention : (app, host?, …) tuples
//! derived from a project's bluebook tree + world file.
//!
//! Routes rendered into lib.rs come straight from `command_bus.bluebook`:
//!
//! ```text
//! POST /route   — Route command : { phrase, params } → event
//! GET  /lexicon — ListPhrases query : the materialized scope set
//! GET  /query   — Query.Run / Query.Read dispatch
//! GET  /health  — HealthCheck query : status + scope size
//! ```
//!
//! Auth guards the mutating route (`/route`) when `auth_scheme` is
//! anything other than `none`. The secret is read through
//! `ctx.env.secret(<AUTH_SECRET_ENV>)`, which workers-rs binds to
//! `wrangler secret put <name>` at runtime.

/// Render the worker crate's `Cargo.toml` as a string.
///
/// `app` is the kebab-case project folder (e.g. "bin-buddy").
/// `storehouse_path` is the Cargo path-dep relative target from
/// `<app>/worker/` up to the hecks/rust checkout.
pub fn emit_cargo_toml(app: &str, storehouse_path: &str) -> String {
    format!(
        "[package]\n\
         name = \"{app}-worker\"\n\
         version = \"0.1.0\"\n\
         edition = \"2021\"\n\
         description = \"{app_title} command bus — WASM Cloudflare Worker exposing the bluebook Dispatch over HTTP.\"\n\
         \n\
         [lib]\n\
         crate-type = [\"cdylib\"]\n\
         \n\
         [dependencies]\n\
         worker                    = \"0.8.3\"\n\
         console_error_panic_hook  = \"0.1\"\n\
         serde                     = {{ version = \"1\", features = [\"derive\"] }}\n\
         serde_json                = \"1\"\n\
         \n\
         # Path-dep on the storehouse library so the worker has the same\n\
         # parser / validator / heki / runtime modules the standalone binary\n\
         # does. Filed in inbox/i105 to switch to a published-crate dependency\n\
         # once storehouse publishes.\n\
         storehouse                = {{ path = \"{storehouse_path}\", default-features = false }}\n\
         \n\
         [profile.release]\n\
         opt-level     = \"s\"      # optimise for binary size, not speed — fits the CF Worker 1MB compressed limit\n\
         strip         = true\n\
         lto           = true\n\
         codegen-units = 1\n",
        app = app,
        app_title = kebab_to_title_case(app),
        storehouse_path = storehouse_path,
    )
}

/// Render the worker crate's `src/lib.rs` as a string.
///
/// The handler exposes the four routes declared in `command_bus.bluebook`
/// — POST /route, GET /lexicon, GET /query, GET /health.
///
/// `auth_scheme` selects the guard on `/route` : `"bearer"` (today's
/// bin-buddy path), `"jwt"` / `"oauth"` (filed for later iterations,
/// rendered today as the same Bearer pattern with a TODO), or `"none"`
/// (no guard). `auth_secret_env` names the env-var the guard reads
/// the secret from via `ctx.env.secret(...)`.
pub fn emit_lib_rs(
    app: &str,
    host: &str,
    auth_scheme: &str,
    auth_secret_env: &str,
) -> String {
    debug_assert_eq!(host, "cf_worker", "only :cf_worker host is wired today");

    let auth_block = render_auth_block(auth_scheme, auth_secret_env);
    let auth_doc = render_auth_doc(auth_scheme, auth_secret_env);
    let app_title = kebab_to_title_case(app);
    let r2_binding = r2_binding_for(app);

    format!(
        "// AUTO-GENERATED by storehouse — do not edit by hand.\n\
         // Source : {app} world file ; regenerate with `storehouse specialize wasm_worker --app {app}`.\n\
         //\n\
         //! {app_title} Worker\n\
         //!\n\
         //! Exposes the {app} bluebook command bus over HTTP. The fetch\n\
         //! handler routes to the four endpoints declared in\n\
         //! `command_bus.bluebook` :\n\
         //!\n\
         //!   POST /route   — Route command : {{ phrase, params }} → event\n\
         //!   GET  /lexicon — ListPhrases query : the materialized scope set\n\
         //!   GET  /query   — Query.Run / Query.Read dispatch\n\
         //!   GET  /health  — HealthCheck query : status + scope size\n\
         //!\n\
         {auth_doc}\
         //! POST /route appends every routed command to the R2 object\n\
         //! `dispatch.heki` via `storehouse::heki_r2::append_record`\n\
         //! (i528 R2 storage adapter). lexicon + query stay stubbed\n\
         //! pending downstream wiring — the bus's catalog still loads\n\
         //! from embedded bluebooks, but the materialised phrase scope\n\
         //! needs a read path through the same R2 layer.\n\
         \n\
         use worker::*;\n\
         \n\
         mod embedded;\n\
         \n\
         #[event(fetch)]\n\
         pub async fn main(req: Request, env: Env, _ctx: Context) -> Result<Response> {{\n\
         {ind}console_error_panic_hook::set_once();\n\
         {ind}Router::new()\n\
         {ind}{ind}.get(\"/health\", health)\n\
         {ind}{ind}.get(\"/lexicon\", lexicon)\n\
         {ind}{ind}.get(\"/query\", query)\n\
         {ind}{ind}.post_async(\"/route\", route)\n\
         {ind}{ind}.run(req, env)\n\
         {ind}{ind}.await\n\
         }}\n\
         \n\
         fn health(_req: Request, _ctx: RouteContext<()>) -> Result<Response> {{\n\
         {ind}let body = serde_json::json!({{\n\
         {ind}{ind}\"service\":            \"{app}-worker\",\n\
         {ind}{ind}\"status\":             \"ok\",\n\
         {ind}{ind}\"bluebooks_embedded\": embedded::BLUEBOOK_COUNT,\n\
         {ind}{ind}\"primary\":            embedded::PRIMARY_BASENAME,\n\
         {ind}}});\n\
         {ind}Response::from_json(&body)\n\
         }}\n\
         \n\
         fn lexicon(_req: Request, _ctx: RouteContext<()>) -> Result<Response> {{\n\
         {ind}// ListPhrases query — returns the materialized phrase scope.\n\
         {ind}// Stubbed pending the R2 storage adapter ; today reports the\n\
         {ind}// embedded bluebook count as a sanity signal.\n\
         {ind}let body = serde_json::json!({{\n\
         {ind}{ind}\"ok\":              false,\n\
         {ind}{ind}\"stage\":           \"stub — pending R2 heki adapter (i104)\",\n\
         {ind}{ind}\"bluebooks_embedded\": embedded::BLUEBOOK_COUNT,\n\
         {ind}}});\n\
         {ind}Response::from_json(&body)\n\
         }}\n\
         \n\
         fn query(_req: Request, _ctx: RouteContext<()>) -> Result<Response> {{\n\
         {ind}// Query dispatch — Query.Run / Query.Read. Stubbed pending R2.\n\
         {ind}let body = serde_json::json!({{\n\
         {ind}{ind}\"ok\":    false,\n\
         {ind}{ind}\"stage\": \"stub — pending R2 heki adapter (i104)\",\n\
         {ind}}});\n\
         {ind}Response::from_json(&body)\n\
         }}\n\
         \n\
         async fn route(mut req: Request, ctx: RouteContext<()>) -> Result<Response> {{\n\
         {auth_block}\
         {ind}// ── Body parse ───────────────────────────────────────────\n\
         {ind}let body: serde_json::Value = match req.json().await {{\n\
         {ind}{ind}Ok(v) => v,\n\
         {ind}{ind}Err(e) => return Response::error(format!(\"bad JSON body : {{}}\", e), 400),\n\
         {ind}}};\n\
         {ind}let phrase = body.get(\"phrase\").and_then(|v| v.as_str()).unwrap_or(\"\").to_string();\n\
         {ind}let params = body.get(\"params\").cloned().unwrap_or(serde_json::Value::Object(serde_json::Map::new()));\n\
         {ind}if phrase.is_empty() {{\n\
         {ind}{ind}return Response::error(\"missing 'phrase' field — expected 'app::domain::Aggregate::Command'\", 400);\n\
         {ind}}}\n\
         \n\
         {ind}// ── Dispatch ────────────────────────────────────────────\n\
         {ind}// V1 surface : every routed command appends to the\n\
         {ind}// dispatch.heki object on R2 so a deployed Worker can\n\
         {ind}// be observed (and replayed) against its event log.\n\
         {ind}// Bluebook-level apply / project lands as the consumers\n\
         {ind}// of dispatch.heki materialise.\n\
         {ind}let bucket = match ctx.env.bucket(\"{r2_binding}\") {{\n\
         {ind}{ind}Ok(b)  => b,\n\
         {ind}{ind}Err(e) => return Response::error(format!(\"r2 binding {r2_binding} unavailable : {{}}\", e), 500),\n\
         {ind}}};\n\
         {ind}let mut attrs = storehouse::heki::Record::new();\n\
         {ind}attrs.insert(\"phrase\".into(), serde_json::Value::String(phrase.clone()));\n\
         {ind}attrs.insert(\"params\".into(), params.clone());\n\
         {ind}let appended = match storehouse::heki_r2::append_record(&bucket, \"dispatch.heki\", &attrs).await {{\n\
         {ind}{ind}Ok(rec) => rec,\n\
         {ind}{ind}Err(e)  => return Response::error(format!(\"r2 append : {{}}\", e), 502),\n\
         {ind}}};\n\
         {ind}let body = serde_json::json!({{\n\
         {ind}{ind}\"ok\":                 true,\n\
         {ind}{ind}\"stage\":              \"appended-to-r2\",\n\
         {ind}{ind}\"record\":             appended,\n\
         {ind}{ind}\"bluebooks_embedded\": embedded::BLUEBOOK_COUNT,\n\
         {ind}}});\n\
         {ind}Response::from_json(&body)\n\
         }}\n",
        app = app,
        app_title = app_title,
        auth_doc = auth_doc,
        auth_block = auth_block,
        r2_binding = r2_binding,
        ind = "    ",
    )
}

/// Convention : a kebab-case app folder maps to an R2 binding named
/// `<APP_UPPER>_R2_BUCKET`. bin-buddy → `BIN_BUDDY_R2_BUCKET`. This
/// matches the env-var naming the world file's `r2 do bucket_env
/// "..." end` block declares and the binding name in wrangler.toml's
/// `[[r2_buckets]]` block. The world file is the source of the
/// convention ; emitting it here keeps the Worker and the world in
/// sync without an extra CLI flag.
fn r2_binding_for(app: &str) -> String {
    format!("{}_R2_BUCKET", app.replace('-', "_").to_uppercase())
}

fn render_auth_doc(auth_scheme: &str, auth_secret_env: &str) -> String {
    if auth_scheme == "none" {
        return String::new();
    }
    format!(
        "//! Auth (POST /route only) : carried by the auth_scheme value the\n\
         //! world file picks ; the auth secret reads through\n\
         //! `ctx.env.secret(\"{auth_secret_env}\")`.\n\
         //!\n",
        auth_secret_env = auth_secret_env,
    )
}

fn render_auth_block(auth_scheme: &str, auth_secret_env: &str) -> String {
    if auth_scheme == "none" {
        return String::new();
    }
    let ind = "    ";
    format!(
        "{ind}// ── Auth ─────────────────────────────────────────────────\n\
         {ind}// auth_scheme = {auth_scheme} ; secret carried in env var {auth_secret_env}.\n\
         {ind}let expected_token = ctx\n\
         {ind}{ind}.env\n\
         {ind}{ind}.secret(\"{auth_secret_env}\")\n\
         {ind}{ind}.map(|s| s.to_string())\n\
         {ind}{ind}.unwrap_or_default();\n\
         {ind}let header_token = req\n\
         {ind}{ind}.headers()\n\
         {ind}{ind}.get(\"Authorization\")\n\
         {ind}{ind}.ok()\n\
         {ind}{ind}.flatten()\n\
         {ind}{ind}.and_then(|h| h.strip_prefix(\"Bearer \").map(|t| t.to_string()))\n\
         {ind}{ind}.unwrap_or_default();\n\
         {ind}if expected_token.is_empty() || header_token != expected_token {{\n\
         {ind}{ind}return Response::error(\"unauthorized — Bearer token mismatch\", 401);\n\
         {ind}}}\n\
         \n",
        ind = ind,
        auth_scheme = auth_scheme,
        auth_secret_env = auth_secret_env,
    )
}

fn kebab_to_title_case(s: &str) -> String {
    s.split('-').map(capitalize).collect::<Vec<_>>().join("-")
}

fn capitalize(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        Some(c) => c.to_uppercase().collect::<String>() + chars.as_str(),
        None => String::new(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn cargo_toml_carries_app_name_and_storehouse_path() {
        let toml = emit_cargo_toml("bin-buddy", "../../hecks/rust");

        assert!(toml.contains("name = \"bin-buddy-worker\""));
        assert!(toml.contains("Bin-Buddy command bus"));
        assert!(toml.contains("crate-type = [\"cdylib\"]"));
        assert!(toml.contains("storehouse                = { path = \"../../hecks/rust\""));
        assert!(toml.contains("opt-level     = \"s\""));
    }

    #[test]
    fn lib_rs_emits_four_routes_per_command_bus_bluebook() {
        let src = emit_lib_rs("bin-buddy", "cf_worker", "bearer", "BIN_BUDDY_API_KEY");

        assert!(src.contains(".get(\"/health\", health)"));
        assert!(src.contains(".get(\"/lexicon\", lexicon)"));
        assert!(src.contains(".get(\"/query\", query)"));
        assert!(src.contains(".post_async(\"/route\", route)"));
    }

    #[test]
    fn lib_rs_emits_bearer_auth_block_with_named_env_var() {
        let src = emit_lib_rs("bin-buddy", "cf_worker", "bearer", "BIN_BUDDY_API_KEY");

        assert!(src.contains(".secret(\"BIN_BUDDY_API_KEY\")"));
        assert!(src.contains("Bearer token mismatch"));
    }

    #[test]
    fn lib_rs_route_wires_r2_append_with_kebab_to_underscore_binding() {
        // i528 R2 storage adapter — POST /route appends the routed
        // command to the dispatch.heki object on the R2 bucket. The
        // binding name follows the world-file convention :
        // bin-buddy → BIN_BUDDY_R2_BUCKET.
        let src = emit_lib_rs("bin-buddy", "cf_worker", "bearer", "BIN_BUDDY_API_KEY");

        assert!(src.contains("ctx.env.bucket(\"BIN_BUDDY_R2_BUCKET\")"),
            "route handler must read the R2 binding for this app");
        assert!(src.contains("storehouse::heki_r2::append_record"),
            "route handler must call into the heki_r2 kernel module");
        assert!(src.contains("\"dispatch.heki\""),
            "route handler appends to the dispatch event log object");
    }

    #[test]
    fn r2_binding_for_handles_kebab_case() {
        assert_eq!(r2_binding_for("bin-buddy"), "BIN_BUDDY_R2_BUCKET");
        assert_eq!(r2_binding_for("hello"),     "HELLO_R2_BUCKET");
        assert_eq!(r2_binding_for("a-b-c"),     "A_B_C_R2_BUCKET");
    }

    #[test]
    fn lib_rs_omits_auth_block_when_scheme_is_none() {
        let src = emit_lib_rs("hello", "cf_worker", "none", "");

        assert!(!src.contains("Bearer token mismatch"));
        assert!(!src.contains("secret("));
    }

    #[test]
    fn lib_rs_reports_service_name_in_health_payload() {
        let src = emit_lib_rs("bin-buddy", "cf_worker", "bearer", "BIN_BUDDY_API_KEY");

        assert!(src.contains("\"service\":            \"bin-buddy-worker\""));
    }

    #[test]
    fn dump_bin_buddy_smoke_to_tmp() {
        // Smoke-dump for eyeball inspection ; not a strict assertion.
        // Writes the rendered Cargo.toml + lib.rs for the bin-buddy world
        // params to /tmp/ so the operator can diff against the existing
        // <bin-buddy>/worker/ tree.
        let cargo = emit_cargo_toml("bin-buddy", "../../hecks/rust");
        let lib = emit_lib_rs("bin-buddy", "cf_worker", "bearer", "BIN_BUDDY_API_KEY");
        let _ = std::fs::write("/tmp/bin_buddy_worker_Cargo.toml", &cargo);
        let _ = std::fs::write("/tmp/bin_buddy_worker_lib.rs", &lib);
    }
}
