//! WASM Cloudflare-Worker emitter — i528 step 8, the second member
//! of the `:codegen` adapter family declared in command_bus.hecksagon.
//!
//! [antibody-exempt: rust/src/specializer/wasm_worker.rs — kernel-floor
//!  codegen emitter. Reads a project's (app, host, auth_scheme,
//!  auth_secret_env, storehouse_path) tuple from its world file and
//!  emits two strings : the worker's Cargo.toml (workspace member,
//!  cdylib, path-dep on storehouse, release profile tuned for the
//!  1MB CF Worker limit) and src/lib.rs (the workers-rs fetch
//!  handler routed to the four endpoints the CommandBus bluebook
//!  declares). Shape declared in codegen/wasm_worker_shape/. Retires
//!  under the broader i78 (specializer-files-as-bluebook) once the
//!  codegen meta-shape itself becomes bluebook-generated.]
//!
//! Sibling to `ruby_command_class` — same `:codegen` adapter family,
//! different target language (Rust → WASM instead of Ruby). The two
//! emitters share the same input convention : (app, host?, …) tuples
//! derived from a project's bluebook tree + world file.
//!
//! Routes rendered into lib.rs come straight from `command_bus.bluebook`:
//!
//! ```text
//! POST /route   — Route command : { phrase, params } → event
//! GET  /lexicon — ListPhrases query : the materialized scope set
//! GET  /query   — Query.Run / Query.Read dispatch
//! GET  /health  — HealthCheck query : status + scope size
//! ```
//!
//! Auth guards the mutating route (`/route`) when `auth_scheme` is
//! anything other than `none`. The secret is read through
//! `ctx.env.secret(<AUTH_SECRET_ENV>)`, which workers-rs binds to
//! `wrangler secret put <name>` at runtime.

/// Render the worker crate's `Cargo.toml` as a string.
///
/// `app` is the kebab-case project folder (e.g. "bin-buddy").
/// `storehouse_path` is the Cargo path-dep relative target from
/// `<app>/worker/` up to the hecks/rust checkout.
pub fn emit_cargo_toml(app: &str, storehouse_path: &str) -> String {
    format!(
        "[package]\n\
         name = \"{app}-worker\"\n\
         version = \"0.1.0\"\n\
         edition = \"2021\"\n\
         description = \"{app_title} command bus — WASM Cloudflare Worker exposing the bluebook Dispatch over HTTP.\"\n\
         \n\
         [lib]\n\
         crate-type = [\"cdylib\"]\n\
         \n\
         [dependencies]\n\
         worker                    = \"0.8.3\"\n\
         console_error_panic_hook  = \"0.1\"\n\
         serde                     = {{ version = \"1\", features = [\"derive\"] }}\n\
         serde_json                = \"1\"\n\
         \n\
         # Path-dep on the storehouse library so the worker has the same\n\
         # parser / validator / heki / runtime modules the standalone binary\n\
         # does. Filed in inbox/i105 to switch to a published-crate dependency\n\
         # once storehouse publishes.\n\
         storehouse                = {{ path = \"{storehouse_path}\", default-features = false }}\n\
         \n\
         [profile.release]\n\
         opt-level     = \"s\"      # optimise for binary size, not speed — fits the CF Worker 1MB compressed limit\n\
         strip         = true\n\
         lto           = true\n\
         codegen-units = 1\n",
        app = app,
        app_title = kebab_to_title_case(app),
        storehouse_path = storehouse_path,
    )
}

/// Render the worker crate's `src/lib.rs` as a string.
///
/// The handler exposes the four routes declared in `command_bus.bluebook`
/// — POST /route, GET /lexicon, GET /query, GET /health.
///
/// `auth_scheme` selects the guard on `/route` : `"bearer"` (today's
/// bin-buddy path), `"jwt"` / `"oauth"` (filed for later iterations,
/// rendered today as the same Bearer pattern with a TODO), or `"none"`
/// (no guard). `auth_secret_env` names the env-var the guard reads
/// the secret from via `ctx.env.secret(...)`.
pub fn emit_lib_rs(
    app: &str,
    host: &str,
    auth_scheme: &str,
    auth_secret_env: &str,
) -> String {
    debug_assert_eq!(host, "cf_worker", "only :cf_worker host is wired today");
    let _ = auth_scheme; // templated worker is bearer (bin-buddy shape)
    let app_title = kebab_to_title_case(app);
    let r2_binding = r2_binding_for(app);
    let header = format!(
        "// AUTO-GENERATED by storehouse — do not edit by hand.\n\
         // Source : {app} embedded bluebooks ; regenerate with `storehouse specialize wasm_worker --app {app}`.\n\
         // [antibody-exempt: {app}/worker/src/lib.rs — kernel-floor WASM Worker emitted by the wasm_worker specializer from codegen/wasm_worker_shape/worker_lib_rs.tmpl ; generated, not hand-written.]\n\
         //\n"
    );
    let body = include_str!("../../../codegen/wasm_worker_shape/worker_lib_rs.tmpl")
        .replace("__APP_TITLE__", &app_title)
        .replace("__AUTH_SECRET_ENV__", auth_secret_env)
        .replace("__R2_BINDING__", &r2_binding)
        .replace("__APP__", app);
    format!("{header}{body}")
}

/// Convention : a kebab-case app folder maps to an R2 binding named
/// `<APP_UPPER>_R2_BUCKET`. bin-buddy → `BIN_BUDDY_R2_BUCKET`. This
/// matches the env-var naming the world file's `r2 do bucket_env
/// "..." end` block declares and the binding name in wrangler.toml's
/// `[[r2_buckets]]` block. The world file is the source of the
/// convention ; emitting it here keeps the Worker and the world in
/// sync without an extra CLI flag.
fn r2_binding_for(app: &str) -> String {
    format!("{}_R2_BUCKET", app.replace('-', "_").to_uppercase())
}

fn kebab_to_title_case(s: &str) -> String {
    s.split('-').map(capitalize).collect::<Vec<_>>().join("-")
}

fn capitalize(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        Some(c) => c.to_uppercase().collect::<String>() + chars.as_str(),
        None => String::new(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn cargo_toml_carries_app_name_and_storehouse_path() {
        let toml = emit_cargo_toml("bin-buddy", "../../hecks/rust");

        assert!(toml.contains("name = \"bin-buddy-worker\""));
        assert!(toml.contains("Bin-Buddy command bus"));
        assert!(toml.contains("crate-type = [\"cdylib\"]"));
        assert!(toml.contains("storehouse                = { path = \"../../hecks/rust\""));
        assert!(toml.contains("opt-level     = \"s\""));
    }

    #[test]
    fn lib_rs_emits_four_routes_per_command_bus_bluebook() {
        let src = emit_lib_rs("bin-buddy", "cf_worker", "bearer", "BIN_BUDDY_API_KEY");

        assert!(src.contains(".get(\"/health\", health)"));
        assert!(src.contains(".get(\"/lexicon\", lexicon)"));
        assert!(src.contains(".get(\"/query\", query)"));
        assert!(src.contains(".post_async(\"/route\", route)"));
    }

    #[test]
    fn lib_rs_emits_bearer_auth_block_with_named_env_var() {
        let src = emit_lib_rs("bin-buddy", "cf_worker", "bearer", "BIN_BUDDY_API_KEY");

        assert!(src.contains(".secret(\"BIN_BUDDY_API_KEY\")"));
        assert!(src.contains("Bearer token mismatch"));
    }

    #[test]
    fn lib_rs_route_wires_r2_append_with_kebab_to_underscore_binding() {
        // i528 R2 storage adapter — POST /route appends the routed
        // command to the dispatch.heki object on the R2 bucket. The
        // binding name follows the world-file convention :
        // bin-buddy → BIN_BUDDY_R2_BUCKET.
        let src = emit_lib_rs("bin-buddy", "cf_worker", "bearer", "BIN_BUDDY_API_KEY");

        assert!(src.contains("ctx.env.bucket(\"BIN_BUDDY_R2_BUCKET\")"),
            "route handler must read the R2 binding for this app");
        assert!(src.contains("storehouse::heki_r2::append_record"),
            "route handler must call into the heki_r2 kernel module");
        assert!(src.contains("\"dispatch.heki\""),
            "route handler appends to the dispatch event log object");
    }

    #[test]
    fn r2_binding_for_handles_kebab_case() {
        assert_eq!(r2_binding_for("bin-buddy"), "BIN_BUDDY_R2_BUCKET");
        assert_eq!(r2_binding_for("hello"),     "HELLO_R2_BUCKET");
        assert_eq!(r2_binding_for("a-b-c"),     "A_B_C_R2_BUCKET");
    }

    #[test]
    fn lib_rs_boots_runtime_from_embedded_bluebooks() {
        // i104 closed — the specializer now emits the full command
        // bus worker (boots a Runtime from embedded bluebooks + seeds
        // fixtures), not the old stub.
        let src = emit_lib_rs("bin-buddy", "cf_worker", "bearer", "BIN_BUDDY_API_KEY");
        assert!(src.contains("boot_runtimes"));
        assert!(src.contains("seed_fixtures"));
        assert!(src.contains("Runtime::boot_with_hecksagons"));
    }

    #[test]
    fn lib_rs_reports_service_name_in_health_payload() {
        let src = emit_lib_rs("bin-buddy", "cf_worker", "bearer", "BIN_BUDDY_API_KEY");

        assert!(src.contains("\"service\":            \"bin-buddy-worker\""));
    }

    #[test]
    fn dump_bin_buddy_smoke_to_tmp() {
        // Smoke-dump for eyeball inspection ; not a strict assertion.
        // Writes the rendered Cargo.toml + lib.rs for the bin-buddy world
        // params to /tmp/ so the operator can diff against the existing
        // <bin-buddy>/worker/ tree.
        let cargo = emit_cargo_toml("bin-buddy", "../../hecks/rust");
        let lib = emit_lib_rs("bin-buddy", "cf_worker", "bearer", "BIN_BUDDY_API_KEY");
        let _ = std::fs::write("/tmp/bin_buddy_worker_Cargo.toml", &cargo);
        let _ = std::fs::write("/tmp/bin_buddy_worker_lib.rs", &lib);
    }
}
