require "fileutils"
Hecks::Chapters.load_aggregates(
  Hecks::Targets::Ruby,
  base_dir: __dir__
)
Hecks::Chapters.load_aggregates(
  Hecks::Targets::Ruby,
  base_dir: File.expand_path("gem_generator", __dir__)
)

module HecksStatic
# HecksStatic::GemGenerator
#
# Generates a complete, self-contained domain project with zero runtime
# dependency on hecks. Orchestrates runtime templates, domain code,
# server, UI, CLI, and infrastructure generation.
#
#   gen = GemGenerator.new(domain, output_dir: "examples")
#   gen.generate  # => path to generated static project
#
class GemGenerator < Hecks::Generator
  include DomainWriter

  def initialize(domain, version: "0.1.0", output_dir: ".")
    @domain = domain
    @version = version
    @output_dir = output_dir
  end

  def generate
    gem_name = @domain.gem_name
    static_name = @domain.name.downcase + "_static_ruby"
    mod = domain_module_name(@domain.name)
    root = File.join(@output_dir, static_name)

    FileUtils.mkdir_p(root)

    RuntimeWriter.new(mod).write(root, gem_name)
    generate_entry_point(root, gem_name, mod)
    generate_aggregates(root, gem_name, mod)
    generate_queries(root, gem_name, mod)
    generate_ports(root, gem_name, mod)
    generate_adapters(root, gem_name, mod)
    generate_services(root, gem_name, mod)
    generate_middleware(root, gem_name, mod)
    generate_server(root, gem_name, mod)
    generate_bin(root, gem_name, mod)
    generate_gemspec(root, gem_name, mod)
    generate_domain_rb(root)

    root
  end

  private

  def generate_domain_rb(root)
    serializer = Hecks::DslSerializer.new(@domain)
    bluebook = Dir[File.join(root, "*Bluebook")].first ||
               File.join(root, "#{@domain.name}Bluebook")
    File.write(bluebook, serializer.serialize)
  end

  def generate_gemspec(root, gem_name, mod)
    content = <<~RUBY
      Gem::Specification.new do |s|
        s.name        = "#{gem_name}"
        s.version     = "#{@version}"
        s.authors     = ["Generated by Hecks"]
        s.summary     = "#{mod} domain model (static)"
        s.files       = Dir["lib/**/*"]
        s.require_paths = ["lib"]
        s.add_dependency "webrick", ">= 1.7"
        s.add_development_dependency "rspec", "~> 3.0"
      end
    RUBY
    File.write(File.join(root, "#{gem_name}.gemspec"), content)

    gemfile = <<~RUBY
      source "https://rubygems.org"
      gem "webrick", ">= 1.7"
    RUBY
    File.write(File.join(root, "Gemfile"), gemfile)
  end

  def generate_entry_point(root, gem_name, mod)
    gen = EntryPointGenerator.new(@domain)
    dir = File.join(root, "lib")
    FileUtils.mkdir_p(dir)
    File.write(File.join(dir, "#{gem_name}.rb"), gen.generate_entry_point(mod, gem_name))
    boot_path = File.join(root, "boot.rb")
    File.write(boot_path, gen.generate_boot(mod, gem_name)) unless File.exist?(boot_path)
  end

  def generate_middleware(root, gem_name, mod)
    template_dir = File.expand_path("../templates", __dir__)
    source = File.read(File.join(template_dir, "validations.rb"))
    File.write(File.join(root, "lib", gem_name, "validations.rb"), source.gsub("__DOMAIN_MODULE__", mod))
  end

  def generate_server(root, gem_name, mod)
    server_dir = File.join(root, "lib", gem_name, "server")
    FileUtils.mkdir_p(server_dir)
    template_dir = File.expand_path("../templates", __dir__)
    # Copy server base template
    source = File.read(File.join(template_dir, "server.rb"))
    File.write(File.join(server_dir, "server.rb"), source.gsub("__DOMAIN_MODULE__", mod))

    # Copy renderer from runtime web_explorer extension
    # Path resolution: try hecksties first (monorepo layout), then legacy hecks_runtime
    explorer_dir = File.expand_path("../../../../../hecksties/lib/hecks/extensions/web_explorer", __dir__)
    explorer_dir = File.expand_path("../../../../hecks_runtime/lib/hecks/extensions/web_explorer", __dir__) unless Dir.exist?(explorer_dir)
    renderer_src = File.read(File.join(explorer_dir, "renderer.rb"))
    renderer_out = renderer_src
      .gsub("module Hecks\n  module WebExplorer", "module #{mod}\n  module Server")
      .gsub("Hecks::WebExplorer", "#{mod}::Server")
    File.write(File.join(server_dir, "renderer.rb"), renderer_out)

    # Copy ERB views
    views_dir = File.join(server_dir, "views")
    FileUtils.mkdir_p(views_dir)
    Dir.glob(File.join(explorer_dir, "views", "*.erb")).each do |erb|
      FileUtils.cp(erb, views_dir)
    end

    # Generate route handlers (JSON API + UI routes)
    File.write(File.join(server_dir, "domain_app.rb"), ServerGenerator.new(@domain).generate(mod, gem_name))
    File.write(File.join(server_dir, "ui_routes.rb"), UIGenerator.new(@domain).generate(mod, gem_name))
  end

  def generate_bin(root, gem_name, mod)
    bin_dir = File.join(root, "bin")
    FileUtils.mkdir_p(bin_dir)
    cmd_name = @domain.name.downcase
    template_dir = File.expand_path("../templates", __dir__)
    cli_script = File.read(File.join(template_dir, "cli.rb"))
      .gsub("__GEM__", gem_name)
      .gsub("__MOD__", mod)
      .gsub("__CMD__", cmd_name)
    path = File.join(bin_dir, cmd_name)
    File.write(path, cli_script)
    File.chmod(0o755, path)
  end
end
end
