Hecks::Chapters.load_aggregates(
  Hecks::Targets::Ruby,
  base_dir: File.expand_path("server_generator", __dir__)
)

module HecksStatic
# HecksStatic::ServerGenerator
#
# Generates a domain-specific HTTP server subclass with routes derived
# from the domain IR. Each aggregate gets GET / and GET /:id routes.
# Each command gets a POST route. Query, scope, specification, and
# event log routes are generated by DomainRoutes. The server also
# mounts a GET /_openapi endpoint.
#
#   gen = ServerGenerator.new(domain)
#   gen.generate("PizzasDomain", "pizzas_domain")
#
class ServerGenerator < Hecks::Generator
  include DomainRoutes

  def initialize(domain)
    @domain = domain
  end

  def generate(mod, gem_name)
    lines = []
    lines << "require_relative \"../runtime/errors\""
    lines << "require_relative \"server\""
    lines << "require_relative \"ui_routes\""
    lines << ""
    lines << "module #{mod}"
    lines << "  module Server"
    lines << "    class DomainApp < App"
    lines << "      include UIRoutes"
    lines << ""
    lines << "      private"
    lines << ""
    lines << "      def mount_routes(server)"
    lines.concat(route_lines)
    lines.concat(domain_behavior_routes)
    lines.concat(openapi_route(mod))
    lines << "        mount_ui_routes(server)"
    lines << "      end"
    lines << "    end"
    lines << "  end"
    lines << "end"
    lines.join("\n") + "\n"
  end

  private

  def route_lines
    lines = []
    @domain.aggregates.each do |agg|
      safe = domain_constant_name(agg.name)
      snake = domain_snake_name(safe)
      plural = domain_aggregate_slug(agg.name)

      # GET /pizzas — list all
      lines << "        server.mount_proc \"/#{plural}\" do |req, res|"
      lines << "          if req.request_method == \"GET\""
      lines << "            items = #{safe}.all.map { |obj| aggregate_to_hash(obj) }"
      lines << "            json_response(res, items)"
      lines << "          else"
      lines << "            res.status = 405"
      lines << "          end"
      lines << "        end"
      lines << ""

      # GET /pizzas/:id — find by ID
      lines << "        server.mount_proc \"/#{plural}/find\" do |req, res|"
      lines << "          id = req.query[\"id\"]"
      lines << "          obj = #{safe}.find(id)"
      lines << "          if obj"
      lines << "            json_response(res, aggregate_to_hash(obj))"
      lines << "          else"
      lines << "            json_error(res, { error: \"NotFound\", message: \"#{safe} not found\" }, status: 404)"
      lines << "          end"
      lines << "        end"
      lines << ""

      # POST /pizzas/:command — one route per command
      agg.commands.each do |cmd|
        cmd_snake = domain_snake_name(cmd.name)
        lines << "        server.mount_proc \"/#{plural}/#{cmd_snake}\" do |req, res|"
        lines << "          begin"
        lines << "            attrs = parse_body(req)"
        lines << "            error = #{domain_module_name(@domain.name)}::Validations.check(\"#{safe}\", \"#{cmd_snake}\", attrs)"
        lines << "            raise error if error"
        lines << "            result = #{safe}.#{cmd_snake}(**attrs)"
        lines << "            json_response(res, aggregate_to_hash(result.aggregate), status: 201)"
        lines << "          rescue #{domain_module_name(@domain.name)}::Error => e"
        lines << "            json_error(res, e)"
        lines << "          end"
        lines << "        end"
        lines << ""
      end
    end
    lines
  end

  def openapi_route(mod)
    paths = {}
    @domain.aggregates.each do |agg|
      safe = domain_constant_name(agg.name)
      snake = domain_snake_name(safe)
      plural = domain_aggregate_slug(agg.name)

      paths["/#{plural}"] = { "get" => { "summary" => "List all #{plural}" } }
      paths["/#{plural}/find"] = { "get" => { "summary" => "Find #{safe} by ID" } }

      agg.commands.each do |cmd|
        cmd_snake = domain_snake_name(cmd.name)
        params = cmd.attributes.map { |a| { "name" => a.name.to_s, "type" => (a.type || "string").to_s } }
        paths["/#{plural}/#{cmd_snake}"] = {
          "post" => { "summary" => cmd.name, "parameters" => params }
        }
      end
    end

    spec = { "openapi" => "3.0.0", "info" => { "title" => mod }, "paths" => paths }

    [
      "        server.mount_proc \"/_openapi\" do |req, res|",
      "          json_response(res, #{spec.inspect})",
      "        end",
      "",
      "        server.mount_proc \"/_validations\" do |req, res|",
      "          json_response(res, #{domain_module_name(@domain.name)}::Validations.rules || {})",
      "        end"
    ]
  end

end
end
