//! Statusline runner — emits Miette's one-line body status to stdout.
//!
//! [antibody-exempt: rust/src/run_statusline/ — Rust runner for the
//!  Statusline capability declared in cli/statusline/. Originally
//!  generated byte-for-byte from codegen/run_statusline_shape/ via
//!  the i147 W7 specializer ; simplified 2026-05-14 to surface only
//!  two signals (heartbeat + multi-inbox). Retires under i78
//!  (specializer-files-as-bluebook) when the specializer itself is
//!  regenerated from a meta-shape.]
//!
//! Fired by `storehouse statusline` (CLI subcommand). Claude Code's
//! statusline-command.sh becomes a 3-line wrapper that exec's this.
//!
//! ## Signals (post 2026-05-14 simplification)
//!
//! Two signals only :
//!   1. **Heartbeat** — `❤️ <beats>` from `tick.heki`'s `cycle` field,
//!      with the heart glyph alternating every 333ms via wall-clock
//!      nanos. The same persistent rhythm the previous renderer used ;
//!      mood / fatigue / inventions / musings / provider / bulb /
//!      coherence ⚠ / last-dispatch breadcrumb were all stripped.
//!   2. **Multi-inbox listing** — `✉️ <init>:<count> ...` across the
//!      five known inboxes (initials hard-coded in `inbox::INBOXES`).
//!      Entries with zero queued cards are omitted so the line stays
//!      compact. When every inbox is empty the envelope segment is
//!      dropped entirely (no orphan separator).
//!
//! Sleep mode is unchanged from pre-simplification — moon glyph +
//! cycle counter + dream narrative render from `consciousness.heki`
//! when the body is asleep. See `sleep::render_sleep`.

mod inbox;
mod sleep;
mod state;
mod time;

use std::env;

use crate::heki;
use self::sleep::render_sleep;
use self::state::{read_state, State};
use self::time::{heart_glyph, Now};

/// Drain stdin (Claude Code harness JSON), chdir to workspace cwd so
/// inbox + bluebook lookups reflect the user's terminal context, then
/// render. Terminal width is read but unused post-simplification (no
/// right-aligned tool-call breadcrumb anymore) — the input parse stays
/// minimal.
pub fn run() {
    use std::io::Read;
    let mut input = String::new();
    let _ = std::io::stdin().read_to_string(&mut input);
    if !input.is_empty() {
        if let Ok(v) = serde_json::from_str::<serde_json::Value>(&input) {
            if let Some(d) = v.pointer("/workspace/current_dir")
                              .and_then(|x| x.as_str()) {
                let _ = env::set_current_dir(d);
            }
        }
    }

    let info = heki::resolve_info_dir();
    let state = read_state(&info);
    let now = Now::wall_clock();

    let line = if state.consciousness == "sleeping" {
        render_sleep(&state, &now)
    } else {
        render_awake(&state, &now)
    };

    println!("{}", line);
}

/// Compose the awake statusline. Two signals : heartbeat + inboxes.
/// When the inbox list is empty (nothing queued anywhere) the
/// envelope segment is omitted so the line doesn't trail
/// with orphan whitespace.
fn render_awake(s: &State, now: &Now) -> String {
    let mut out = format!("{} {}", heart_glyph(now), format_beats(s.beats_raw));
    let inboxes = inbox::render_inbox_list();
    if !inboxes.is_empty() {
        out.push_str(&format!("  ✉️ {}", inboxes));
    }
    out
}

/// Format beat count : ≥1M → "X.XXm" ; ≥1k → "X.XXk" ; else raw.
fn format_beats(b: i64) -> String {
    if b >= 1_000_000 {
        format!("{:.2}m", (b as f64) / 1_000_000.0)
    } else if b >= 1_000 {
        format!("{:.2}k", (b as f64) / 1_000.0)
    } else {
        b.to_string()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn beats_format_thresholds() {
        assert_eq!(format_beats(0), "0");
        assert_eq!(format_beats(999), "999");
        assert_eq!(format_beats(1_000), "1.00k");
        assert_eq!(format_beats(82_416), "82.42k");
        assert_eq!(format_beats(1_500_000), "1.50m");
    }

    #[test]
    fn awake_render_strips_mood_fatigue_breadcrumb() {
        // Hermeticity : neutralise HOME so the inbox walk against
        // INBOXES finds no real cards, regardless of where cargo runs.
        std::env::set_var("HOME", "/tmp/hecks_statusline_test_no_home");
        let s = State {
            consciousness: "attentive".into(),
            beats_raw: 1234,
            ..Default::default()
        };
        let now = Now { secs: 0, nanos_total: 0 };
        let line = render_awake(&s, &now);

        // Heartbeat present.
        assert!(line.contains("1.23k"), "beats must render — got: {}", line);

        // None of the stripped signals leak in : mood words, fatigue
        // words, mood/fatigue icons, the hammer crumb, the coherence
        // ⚠ glyph, the bulb 💡, the invention 🔬, the musing 💭, any
        // provider badge.
        for forbidden in [
            "focused", "groggy", "drifting", "refreshed", "excited", "curious",
            "rested", "limber", "tuned", "tired", "exhausted", "spent",
            "😊", "🤩", "🎯", "🤔", "🌀", "✨", "😐",
            "🌿", "⚡", "🥱", "😩", "🫠",
            "🛠️", "⚠", "💡", "🔬", "💭", "🤖", "🦙",
        ] {
            assert!(
                !line.contains(forbidden),
                "stripped signal '{}' leaked into: {}", forbidden, line
            );
        }
    }

    #[test]
    fn awake_render_includes_inboxes_when_seeded() {
        // Build a fake HOME with a single inbox containing one queued
        // card. "gl" is first in INBOXES so it owns the slot.
        let tmp = std::env::temp_dir().join(format!(
            "statusline_inbox_seed_{}", std::process::id()
        ));
        let inbox_dir = tmp.join("Projects/hecks/hecks_conception/inbox");
        std::fs::create_dir_all(&inbox_dir).unwrap();
        std::fs::write(
            inbox_dir.join("test.md"),
            "---\nstatus: queued\nref: test\n---\nbody\n",
        ).unwrap();
        std::env::set_var("HOME", &tmp);

        let s = State {
            consciousness: "attentive".into(),
            beats_raw: 500,
            ..Default::default()
        };
        let now = Now { secs: 0, nanos_total: 0 };
        let line = render_awake(&s, &now);
        assert!(line.contains("✉️ gl:1"), "expected gl:1 in: {}", line);
        assert!(!line.contains("•"), "dot separator should be gone in: {}", line);

        let _ = std::fs::remove_dir_all(&tmp);
    }

    #[test]
    fn awake_render_omits_inbox_section_when_all_zero() {
        // No queued cards anywhere ⇒ no envelope, no separator —
        // line is just heartbeat. Pin HOME to a no-inbox tempdir.
        let tmp = std::env::temp_dir().join(format!(
            "statusline_inbox_empty_{}", std::process::id()
        ));
        std::fs::create_dir_all(&tmp).unwrap();
        std::env::set_var("HOME", &tmp);

        let s = State { beats_raw: 42, ..Default::default() };
        let now = Now { secs: 0, nanos_total: 0 };
        let line = render_awake(&s, &now);
        assert!(!line.contains("✉️"), "no envelope expected: {}", line);
        assert!(!line.contains("•"), "no separator expected: {}", line);

        let _ = std::fs::remove_dir_all(&tmp);
    }
}
