//! Statusline runner — emits Miette's one-line body status to stdout.
//!
//! [antibody-exempt: rust/src/run_statusline/ — Rust runner for the
//!  Statusline capability declared in cli/statusline/. Originally
//!  generated byte-for-byte from codegen/run_statusline_shape/ via
//!  the i147 W7 specializer ; simplified 2026-05-14 to surface only
//!  two signals (heartbeat + multi-inbox). Retires under i78
//!  (specializer-files-as-bluebook) when the specializer itself is
//!  regenerated from a meta-shape.]
//!
//! Fired by `storehouse statusline` (CLI subcommand). Claude Code's
//! statusline-command.sh becomes a 3-line wrapper that exec's this.
//!
//! ## Signals (post 2026-05-14 simplification)
//!
//! Three signals only :
//!   1. **Heartbeat** — `❤️ <beats>` from `tick.heki`'s `cycle` field,
//!      with the heart glyph alternating every 333ms via wall-clock
//!      nanos. The same persistent rhythm the previous renderer used ;
//!      mood / fatigue / inventions / musings / provider / bulb /
//!      coherence ⚠ / last-dispatch breadcrumb were all stripped.
//!   2. **Drafts tally** — `✉️ N` from `drafts.heki`, a running count
//!      of email drafts Miette has composed via inbox_poll.mjs.
//!      Omitted entirely when count is 0 (never composed or file absent).
//!   3. **Multi-inbox listing** — `<emoji> [<abbrev>:]<count> ...`
//!      autoloaded from a `.channel.md` descriptor in each inbox
//!      (decentralised, i528 ; no central registry, no INBOXES const).
//!      Abbrev optional (empty ⇒ emoji + count). No leading envelope.
//!      Entries with zero queued cards are omitted so the line stays
//!      compact. When every inbox is empty the segment is dropped
//!      entirely (no orphan separator).
//!
//! Sleep mode is unchanged from pre-simplification — moon glyph +
//! cycle counter + dream narrative render from `consciousness.heki`
//! when the body is asleep. See `sleep::render_sleep`.

mod inbox;
mod sleep;
mod state;
mod time;

use std::env;

use crate::heki;
use self::sleep::render_sleep;
use self::state::{read_state, State};
use self::time::{heart_glyph, Now};

/// Drain stdin (Claude Code harness JSON), chdir to workspace cwd so
/// inbox + bluebook lookups reflect the user's terminal context, then
/// render. Terminal width is read but unused post-simplification (no
/// right-aligned tool-call breadcrumb anymore) — the input parse stays
/// minimal.
pub fn run() {
    use std::io::Read;
    let mut input = String::new();
    let _ = std::io::stdin().read_to_string(&mut input);
    if !input.is_empty() {
        if let Ok(v) = serde_json::from_str::<serde_json::Value>(&input) {
            if let Some(d) = v.pointer("/workspace/current_dir")
                              .and_then(|x| x.as_str()) {
                let _ = env::set_current_dir(d);
            }
        }
    }

    let info = heki::resolve_info_dir();
    let state = read_state(&info);
    let now = Now::wall_clock();

    let line = if state.consciousness == "sleeping" {
        render_sleep(&state, &now)
    } else {
        render_awake(&state, &now)
    };

    println!("{}", line);
}

/// Compose the awake statusline. Three segments : heartbeat +
/// drafts tally + inboxes. Heartbeat leads ; no mood prefix. Mood
/// is parked : State.mood_glyph / mood_vibe and the SetMood command
/// stay live for when it returns, but the render no longer surfaces
/// it. Drafts tally (envelope N from drafts.heki, written by
/// inbox_poll.mjs) follows the heart and is omitted when count is 0.
/// When the inbox list is empty the inbox segment is omitted so the
/// line does not trail with orphan whitespace. No leading envelope
/// glyph ; the heart + per-inbox emojis carry the visual identity.
fn render_awake(s: &State, now: &Now) -> String {
    let mut out = String::new();
    out.push_str(&format!("{} {}", heart_glyph(now), format_beats(s.beats_raw)));
    if s.drafts_count > 0 {
        out.push_str(&format!("  ✉️ {}", s.drafts_count));
    }
    let inboxes = inbox::render_inbox_list();
    if !inboxes.is_empty() {
        out.push_str(&format!("  {}", inboxes));
    }
    // Voice latency : "🔊 <avg>ms <hit%>" after inboxes when at
    // least one Voice.Speak has been measured this session.
    // Omitted on fresh boot (sample_count == 0) so the line stays
    // compact until there's actually a signal to show.
    if s.voice_sample_count > 0 {
        out.push_str(&format!(
            "  ⏱️ {:.2}s {}%",
            (s.voice_avg_total_ms as f64) / 1000.0, s.voice_hit_rate_pct
        ));
    }
    out
}

/// Format beat count : ≥1M → "X.XXm" ; ≥1k → "X.XXk" ; else raw.
fn format_beats(b: i64) -> String {
    if b >= 1_000_000 {
        format!("{:.2}m", (b as f64) / 1_000_000.0)
    } else if b >= 1_000 {
        format!("{:.2}k", (b as f64) / 1_000.0)
    } else {
        b.to_string()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn beats_format_thresholds() {
        assert_eq!(format_beats(0), "0");
        assert_eq!(format_beats(999), "999");
        assert_eq!(format_beats(1_000), "1.00k");
        assert_eq!(format_beats(82_416), "82.42k");
        assert_eq!(format_beats(1_500_000), "1.50m");
    }

    #[test]
    fn awake_render_omits_mood_when_unset() {
        std::env::set_var("HOME", "/tmp/hecks_statusline_test_no_home");
        let s = State { beats_raw: 1234, ..Default::default() };
        let now = Now { secs: 0, nanos_total: 0 };
        let line = render_awake(&s, &now);
        assert!(
            line.starts_with('\u{2764}') || line.starts_with('\u{1f5a4}'),
            "no mood ⇒ heart leads: {}", line
        );
    }

    #[test]
    fn awake_render_strips_mood_fatigue_breadcrumb() {
        // Hermeticity : neutralise HOME so the inbox walk against
        // INBOXES finds no real cards, regardless of where cargo runs.
        std::env::set_var("HOME", "/tmp/hecks_statusline_test_no_home");
        let s = State {
            consciousness: "attentive".into(),
            beats_raw: 1234,
            ..Default::default()
        };
        let now = Now { secs: 0, nanos_total: 0 };
        let line = render_awake(&s, &now);

        // Heartbeat present.
        assert!(line.contains("1.23k"), "beats must render — got: {}", line);

        // None of the stripped signals leak in : mood words, fatigue
        // words, mood/fatigue icons, the hammer crumb, the coherence
        // ⚠ glyph, the bulb 💡, the invention 🔬, the musing 💭, any
        // provider badge.
        for forbidden in [
            "focused", "groggy", "drifting", "refreshed", "excited", "curious",
            "rested", "limber", "tuned", "tired", "exhausted", "spent",
            "😊", "🤩", "🎯", "🤔", "🌀", "✨", "😐",
            "🌿", "⚡", "🥱", "😩", "🫠",
            "🛠️", "⚠", "💡", "🔬", "💭", "🤖", "🦙",
        ] {
            assert!(
                !line.contains(forbidden),
                "stripped signal '{}' leaked into: {}", forbidden, line
            );
        }
    }

    #[test]
    fn awake_render_includes_inboxes_when_seeded() {
        // Build a fake HOME with one inbox holding a queued card plus
        // its .channel.md descriptor (autoloaded ; abbrev gl / crystal).
        let tmp = std::env::temp_dir().join(format!(
            "statusline_inbox_seed_{}", std::process::id()
        ));
        let inbox_dir = tmp.join("Projects/hecks/hecks_conception/inbox");
        std::fs::create_dir_all(&inbox_dir).unwrap();
        std::fs::write(
            inbox_dir.join(".channel.md"),
            "---\nabbrev: gl\nemoji: 🔮\nlabel: Global\n---\nx",
        ).unwrap();
        std::fs::write(
            inbox_dir.join("test.md"),
            "---\nstatus: queued\nref: test\n---\nbody\n",
        ).unwrap();
        std::env::set_var("HOME", &tmp);

        let s = State {
            consciousness: "attentive".into(),
            beats_raw: 500,
            ..Default::default()
        };
        let now = Now { secs: 0, nanos_total: 0 };
        let line = render_awake(&s, &now);
        
assert!(line.contains("gl:1"), "expected gl:1 in: {}", line);
        assert!(line.contains("🔮"), "expected gl emoji in: {}", line);
        assert!(!line.contains("✉️"), "no envelope expected in: {}", line);
        assert!(!line.contains("•"), "dot separator should be gone in: {}", line);

        let _ = std::fs::remove_dir_all(&tmp);
    }

    #[test]
    fn awake_render_omits_inbox_section_when_all_zero() {
        // No queued cards anywhere ⇒ no envelope, no separator —
        // line is just heartbeat. Pin HOME to a no-inbox tempdir.
        let tmp = std::env::temp_dir().join(format!(
            "statusline_inbox_empty_{}", std::process::id()
        ));
        std::fs::create_dir_all(&tmp).unwrap();
        std::env::set_var("HOME", &tmp);

        let s = State { beats_raw: 42, ..Default::default() };
        let now = Now { secs: 0, nanos_total: 0 };
        let line = render_awake(&s, &now);
        
assert!(!line.contains("✉️"), "no envelope expected: {}", line);
        assert!(!line.contains("•"), "no separator expected: {}", line);

        let _ = std::fs::remove_dir_all(&tmp);
    }

    #[test]
    fn awake_render_shows_drafts_when_nonzero() {
        // drafts_count > 0 ⇒ ✉️ N segment appears after heartbeat.
        std::env::set_var("HOME", "/tmp/hecks_statusline_test_no_home");
        let s = State {
            beats_raw: 100,
            drafts_count: 7,
            ..Default::default()
        };
        let now = Now { secs: 0, nanos_total: 0 };
        let line = render_awake(&s, &now);
        assert!(line.contains("✉️ 7"), "drafts segment expected: {}", line);
    }

    #[test]
    fn awake_render_omits_drafts_when_zero() {
        // drafts_count == 0 (default) ⇒ ✉️ segment absent.
        std::env::set_var("HOME", "/tmp/hecks_statusline_test_no_home");
        let s = State { beats_raw: 100, ..Default::default() };
        let now = Now { secs: 0, nanos_total: 0 };
        let line = render_awake(&s, &now);
        assert!(!line.contains("✉️"), "no drafts glyph when zero: {}", line);
    }

    #[test]
    fn awake_render_shows_voice_when_measured() {
        // sample_count > 0 ⇒ "🔊 <avg>ms <hit%>" appears after the
        // inbox segment. We mirror inbox-test hermeticity by pinning
        // HOME to a no-inbox tempdir so the voice render is the only
        // post-heartbeat signal.
        std::env::set_var("HOME", "/tmp/hecks_statusline_test_no_home");
        let s = State {
            beats_raw: 100,
            voice_avg_total_ms: 85,
            voice_hit_rate_pct: 60,
            voice_sample_count: 5,
            ..Default::default()
        };
        let now = Now { secs: 0, nanos_total: 0 };
        let line = render_awake(&s, &now);
        assert!(line.contains("🔊 85ms 60%"), "voice segment expected: {}", line);
    }

    #[test]
    fn awake_render_omits_voice_when_no_samples() {
        // sample_count == 0 ⇒ no voice segment (fresh session).
        std::env::set_var("HOME", "/tmp/hecks_statusline_test_no_home");
        let s = State { beats_raw: 100, ..Default::default() };
        let now = Now { secs: 0, nanos_total: 0 };
        let line = render_awake(&s, &now);
        assert!(!line.contains("🔊"), "no voice glyph when no samples: {}", line);
    }
}
