//! Phase 4b — RegenerateAgentDefs
//!
//! [antibody-exempt: rust/src/run_boot/agent_defs.rs — boot-pipeline runner,
//!  sibling of run_boot/system_prompt.rs. Projects the AgentInstrumentation
//!  source (door.md + AgentDefinition fixtures + roles/<name>.md) into the
//!  subagent instrumentation artifacts. Kernel-floor glue that writes a
//!  generated surface from bluebook source ; retires with the run_boot
//!  pipeline under i78/i145, same as system_prompt.rs.]
//!
//! WHY this exists : the storehouse-door routing convention (every tool call
//! goes through `storehouse__dispatch` because the macrophage denies native
//! tools) used to live ONLY in Miette's system prompt, which subagents do NOT
//! inherit. So a spawned Explore/sidequest agent tried native tools, was
//! denied, and gave up. This runner makes the convention a single shared
//! fragment injected automatically into:
//!
//!   1. BOTH CLAUDE.md files (hecks/CLAUDE.md + hecks_conception/CLAUDE.md),
//!      between generated markers — inherited by EVERY subagent (built-in
//!      Explore/Plan/general-purpose and custom).
//!   2. Each custom `.claude/agents/<name>.md` def — frontmatter (from the
//!      AgentDefinition fixtures) + the shared door fragment + the authored
//!      role body (roles/<name>.md).
//!
//! Run every boot, so the instrumentation can never drift from the governance
//! reality and there is nothing to remember. `door_fragment()` is also the
//! source the system_prompt runner resolves `{{door}}` from, so Miette's
//! prompt and the agents share ONE door fragment.

use std::fs;
use std::path::{Path, PathBuf};

const BEGIN: &str = "<!-- BEGIN storehouse-door (generated by agent_instrumentation) -->";
const END: &str = "<!-- END storehouse-door -->";

/// Directory holding the AgentInstrumentation source (door.md, fixtures,
/// roles/). Resolved off `heki::repo_root()` so it works wherever boot runs.
fn source_dir() -> Option<PathBuf> {
    Some(
        crate::heki::repo_root()?
            .join("hecks_conception/aggregates/framework/agent_instrumentation"),
    )
}

/// The shared door fragment (door.md), read verbatim. Empty when absent —
/// callers treat empty as "skip" so a missing fragment never injects a blank
/// block. Also resolves `{{door}}` in the system-prompt runner.
pub fn door_fragment() -> String {
    source_dir()
        .map(|d| d.join("door.md"))
        .and_then(|p| fs::read_to_string(p).ok())
        .unwrap_or_default()
}

/// Regenerate every subagent instrumentation artifact. Returns the number of
/// `.claude/agents/*.md` defs written (used by vitals). Never panics ; each
/// failure emits a stderr line and boot continues.
pub fn render() -> usize {
    let Some(dir) = source_dir() else {
        eprintln!("  ⚠ agent_defs: cannot resolve repo root");
        return 0;
    };
    let door = door_fragment();
    if door.trim().is_empty() {
        eprintln!("  ⚠ agent_defs: door.md missing/empty at {} — skipping", dir.display());
        return 0;
    }
    let Some(hecks_root) = crate::heki::repo_root() else { return 0; };

    // 1) Inject the shared door block into both CLAUDE.md files (inherited by
    //    every subagent, built-in and custom).
    inject_claude_md(&hecks_root.join("CLAUDE.md"), &door);
    inject_claude_md(&hecks_root.join("hecks_conception/CLAUDE.md"), &door);

    // 2) Generate each custom .claude/agents/<name>.md from the fixtures.
    let fixtures_path = dir.join("agent_instrumentation.fixtures");
    let source = match fs::read_to_string(&fixtures_path) {
        Ok(s) => s,
        Err(e) => {
            eprintln!("  ⚠ agent_defs: fixtures not found at {} ({})", fixtures_path.display(), e);
            return 0;
        }
    };
    let parsed = crate::fixtures_parser::parse(&source);
    let agents_dir = hecks_root.join(".claude/agents");
    if let Err(e) = fs::create_dir_all(&agents_dir) {
        eprintln!("  ⚠ agent_defs: mkdir {} failed ({})", agents_dir.display(), e);
        return 0;
    }

    let mut written = 0usize;
    for f in parsed.fixtures.iter().filter(|f| f.aggregate_name == "AgentDefinition") {
        let get = |k: &str| {
            f.attributes
                .iter()
                .find(|(a, _)| a == k)
                .map(|(_, v)| v.clone())
                .unwrap_or_default()
        };
        let name = get("name");
        if name.is_empty() {
            continue;
        }
        let role_rel = get("role_body");
        let role_body = role_rel
            .is_empty()
            .then(String::new)
            .unwrap_or_else(|| fs::read_to_string(dir.join(&role_rel)).unwrap_or_default());

        // The door convention is NOT embedded here — it is delivered to EVERY
        // subagent (built-in + custom) by the SubagentStart hook
        // (bin/subagent-door-hook), which reads the SAME door.md. So a def
        // carries only frontmatter + authored role body, and the door appears
        // exactly once in the spawned agent's context.
        let md = format!(
            "---\nname: {name}\ndescription: {desc}\nmodel: {model}\n---\n\n\
             <!-- GENERATED by the agent_instrumentation boot runner — do not hand-edit. \
             Source: hecks_conception/aggregates/framework/agent_instrumentation/roles/{role_rel} . \
             The storehouse-door convention is injected separately by the SubagentStart hook. -->\n\n{role}\n",
            name = name,
            desc = get("description"),
            model = get("model"),
            role_rel = role_rel,
            role = role_body.trim_end(),
        );
        let dest = agents_dir.join(format!("{}.md", name));
        match fs::write(&dest, &md) {
            Ok(_) => written += 1,
            Err(e) => eprintln!("  ⚠ agent_defs: write {} failed ({})", dest.display(), e),
        }
    }
    written
}

/// Idempotently replace (or append) the marker-delimited door block in a
/// CLAUDE.md. Replaces the span from BEGIN to END (inclusive) when both
/// markers are present ; appends a fresh block otherwise. A no-op when the
/// file already holds the identical block.
fn inject_claude_md(path: &Path, door: &str) {
    let block = format!("{}\n{}\n{}", BEGIN, door.trim_end(), END);
    let existing = fs::read_to_string(path).unwrap_or_default();
    let updated = match (existing.find(BEGIN), existing.find(END)) {
        (Some(b), Some(e)) if e >= b => {
            let end_idx = e + END.len();
            format!("{}{}{}", &existing[..b], block, &existing[end_idx..])
        }
        _ if existing.trim().is_empty() => format!("{}\n", block),
        _ => format!("{}\n\n{}\n", existing.trim_end(), block),
    };
    if updated != existing {
        if let Err(err) = fs::write(path, &updated) {
            eprintln!("  ⚠ agent_defs: write {} failed ({})", path.display(), err);
        }
    }
}
