  # = Hecks::Utils
  #
  # Shared utility functions used across the Hecks framework. Provides constant
  # sanitization, underscore conversion, type labeling, keyword detection,
  # block source extraction, and object serialization.
  #
  # All methods are defined as +module_function+, so they can be called as
  # either +Hecks::Utils.underscore(str)+ or included into a class.
  #
  # This is an infrastructure layer module consumed by generators, DSL builders,
  # domain services, and the CLI.
  #
  # == Usage
  #
  #   Hecks::Utils.sanitize_constant("My Pizza")  # => "MyPizza"
  #   Hecks::Utils.underscore("PizzaDomain")       # => "pizza_domain"
  #   Hecks::Utils.ruby_keyword?("class")          # => true
  #
module Hecks
  # Hecks::Utils
  #
  # Shared utility functions: constant sanitization, underscore conversion, keyword detection, and serialization.
  #
  module Utils
    # Ruby reserved keywords that cannot be used as bare keyword parameters
    # in method signatures (e.g. +def initialize(class:)+ is invalid syntax).
    # Used by generators to detect attribute names that need special handling.
    RUBY_KEYWORDS = %w[
      __FILE__ __LINE__ __ENCODING__
      BEGIN END
      alias and begin break case class def defined? do else elsif end
      ensure false for if in module next nil not or redo rescue retry
      return self super then true undef unless until when while yield
    ].freeze

    # Attributes that are auto-generated by aggregate classes and should
    # not be duplicated in +attr_reader+ declarations or constructor params.
    # Currently only includes "id" since all aggregates get an auto-generated ID.
    RESERVED_AGGREGATE_ATTRS = %w[id].freeze

    module_function

    # Sanitizes a string into a valid Ruby constant name in PascalCase.
    # Removes special characters, handles leading digits (moves them to end),
    # capitalizes word segments, and falls back to "Unnamed" for empty input.
    #
    # @param name [String, Symbol] the raw name to sanitize
    # @return [String] a valid PascalCase Ruby constant name
    #
    # @example Basic conversions
    #   sanitize_constant("pizza")     # => "Pizza"
    #   sanitize_constant("My Pizza")  # => "MyPizza"
    #   sanitize_constant("My-Pizza")  # => "MyPizza"
    #
    # @example Edge cases
    #   sanitize_constant("3DModel")   # => "Model3D"  (leading digit moved)
    #   sanitize_constant("My.App")    # => "MyApp"
    #   sanitize_constant("My!App?")   # => "MyApp"
    #   sanitize_constant("")          # => "Unnamed"
    def sanitize_constant(name)
      # Remove characters not valid in Ruby identifiers (keep letters, digits, underscores, spaces, hyphens as separators)
      cleaned = name.to_s.gsub(/[^a-zA-Z0-9_\s-]/, "")

      # Split on word boundaries (spaces, hyphens, underscores) and capitalize each segment
      parts = cleaned.split(/[\s\-_]+/).reject(&:empty?)

      return "Unnamed" if parts.empty?

      # Capitalize each segment for PascalCase
      result = parts.map { |p| p[0].upcase + p[1..].to_s }.join

      # If the result starts with a digit, move leading digits to the end
      if result.match?(/\A\d/)
        leading_digits = result[/\A\d+/]
        rest = result.sub(/\A\d+/, "")
        if rest.empty?
          result = "N#{leading_digits}"
        else
          result = rest[0].upcase + rest[1..].to_s + leading_digits
        end
      end

      result
    end

    # Checks whether the given attribute name is a Ruby reserved keyword
    # that cannot be used as a bare keyword parameter in method signatures.
    #
    # @param name [String, Symbol] the attribute name to check
    # @return [Boolean] true if the name is a Ruby keyword
    #
    # @example
    #   ruby_keyword?("class")  # => true
    #   ruby_keyword?("name")   # => false
    def ruby_keyword?(name)
      RUBY_KEYWORDS.include?(name.to_s)
    end

    # Converts a PascalCase string to space-separated human-readable form.
    #
    # @param name [String, Symbol] the PascalCase name to humanize
    # @return [String] human-readable form (e.g., "Create Pizza")
    #
    # @example
    #   humanize("CreatePizza")  # => "Create Pizza"
    #   humanize("IssueLoan")    # => "Issue Loan"
    #   humanize(:by_category)   # => "by category"
    def humanize(name)
      name.to_s.gsub(/([A-Z])/, ' \1').strip
    end

    # Converts a PascalCase or camelCase string to snake_case.
    # Handles consecutive uppercase letters (e.g., "HTMLParser" => "html_parser").
    #
    # @param str [String] the string to convert
    # @return [String] the snake_case version
    #
    # @example
    #   underscore("PizzaDomain")  # => "pizza_domain"
    #   underscore("HTMLParser")   # => "html_parser"
    #   underscore("getURL")       # => "get_url"
    def underscore(str)
      str.to_s.gsub(/([A-Z]+)([A-Z][a-z])/, '\1_\2')
         .gsub(/([a-z\d])([A-Z])/, '\1_\2')
         .downcase
    end

    # Extracts the short class name from a fully-qualified constant path.
    # Works with both string names and objects/classes.
    #
    # @param obj [String, Class, Object] a constant name, class, or instance
    # @return [String] the last component (e.g., "CreatedPizza")
    #
    # @example
    #   const_short_name("PizzasDomain::Pizza::Events::CreatedPizza")  # => "CreatedPizza"
    #   const_short_name(PizzasDomain::Pizza)                          # => "Pizza"
    #   const_short_name(some_event)                                   # => "PlacedOrder"
    def const_short_name(obj)
      name = case obj
             when String then obj
             when Class, Module then obj.name
             else obj.class.name
             end
      name.to_s.split("::").last
    end

    # Returns a human-readable type label for a domain attribute.
    # Wraps list and reference types in descriptive notation.
    #
    # @param attr [Hecks::BluebookModel::Structure::Attribute] the attribute
    #   to label (must respond to +list?+, +reference?+, and +type+)
    # @return [String] the type label (e.g., "String", "list_of(Topping)",
    #   "reference_to(Order)")
    def type_label(attr)
      if attr.list?
        "list_of(#{attr.type})"
      else
        attr.type.to_s
      end
    end

    # Extracts the source code of a block as a string by reading the source
    # file at the block's location. Used by the domain inspector and
    # introspection tools to display guard/query logic.
    #
    # Handles both single-line blocks (+do ... end+ on one line) and
    # multi-line blocks (collecting body lines between +do+ and +end+).
    #
    # @param block [Proc, nil] the block whose source to extract. If nil,
    #   returns "true".
    # @return [String] the block body source code, or "true" if the block
    #   is nil or source extraction fails
    def block_source(block)
      return "true" unless block
      file, start_line = block.source_location
      lines = File.readlines(file)

      # Single-line block: `query "Foo" do where(x: 1) end`
      first = lines[start_line - 1].strip
      if first.match?(/\bdo\b.*\bend\s*$/)
        return first.sub(/^.*?\bdo\s*(\|[^|]*\|\s*)?/, "").sub(/\s*end\s*$/, "").strip
      end

      # Multi-line block: collect body lines between do and end
      body_lines = []
      depth = 0
      lines[start_line..-1].each do |l|
        stripped = l.strip
        break if depth == 0 && stripped == "end"
        body_lines << stripped
        # Only count block-opening keywords at the start of a line.
        # Inline modifiers (raise "x" unless y) don't open blocks.
        depth += 1 if stripped.match?(/\A(do|def|class|module|if|unless|case|begin)\b/)
        depth -= 1 if stripped == "end"
      end
      body_lines.reject(&:empty?).join("\n")
    rescue StandardError
      "true"
    end

    # Returns the attribute names for a Hecks domain object. Prefers
    # the +hecks_attributes+ class method (set by the Model mixin) for
    # accurate metadata. Falls back to introspecting +initialize+ parameters
    # if +hecks_attributes+ is not available.
    #
    # Always includes +:id+ as the first attribute. Appends +:created_at+
    # and +:updated_at+ if the object responds to +created_at+.
    #
    # @param obj [Object, Class] a domain object instance or class
    # @return [Array<Symbol>] ordered list of attribute names
    def object_attr_names(obj)
      klass = obj.is_a?(Class) ? obj : obj.class
      names = [:id]
      if klass.respond_to?(:hecks_attributes)
        names += klass.hecks_attributes.map(&:name)
      else
        klass.instance_method(:initialize).parameters.each do |_, name|
          names << name if name && name != :id
        end
      end
      names += [:created_at, :updated_at] if obj.respond_to?(:created_at)
      names
    end

    # Extracts the +def call+ method body from a Ruby source code string.
    # Returns the full method text from +def call+ to its matching +end+,
    # tracking nesting depth to handle inner blocks correctly.
    #
    # Used by the domain inspector to display command implementation source.
    #
    # @param source [String, nil] Ruby source code containing a +def call+ method
    # @return [String, nil] the extracted method source (including +def call+
    #   and +end+ lines), or nil if no +call+ method is found or source is nil
    #
    # @example
    #   source = "  def call\n    Pizza.new(name: name)\n  end\n"
    #   extract_call_method(source)
    #   # => "  def call\n    Pizza.new(name: name)\n  end"
    def extract_call_method(source)
      return nil unless source
      lines = source.lines
      start_idx = lines.index { |l| l.strip.match?(/\Adef call\b/) }
      return nil unless start_idx

      # Track nesting: `def call` itself is the first opener
      depth = 1
      end_idx = nil
      lines[(start_idx + 1)..].each_with_index do |line, i|
        stripped = line.strip
        # Count block-opening keywords at start of line (not inline modifiers)
        if stripped.match?(/\A(def|class|module|if|unless|case|begin|while|until|for)\b/)
          depth += 1
        end
        depth += 1 if stripped.match?(/\bdo\s*(\|[^|]*\|)?\s*$/)
        depth -= 1 if stripped == "end"
        if depth == 0
          end_idx = start_idx + 1 + i
          break
        end
      end
      return nil unless end_idx
      lines[start_idx..end_idx].join.rstrip
    end

    # Serializes a Hecks domain object to a Hash using its attribute metadata.
    # Keys are strings, values are the raw attribute values from the object.
    #
    # @param obj [Object] a domain object instance (aggregate, entity, or value object)
    # @return [Hash{String => Object}] the serialized attribute hash
    #
    # @example
    #   pizza = Pizza.new(name: "Margherita", size: "large")
    #   Hecks::Utils.serialize_object(pizza)
    #   # => {"id" => "abc-123", "name" => "Margherita", "size" => "large"}
    def serialize_object(obj)
      object_attr_names(obj).each_with_object({}) do |name, h|
        h[name.to_s] = obj.send(name) if obj.respond_to?(name)
      end
    end

    # Resolves a relative path under a root directory, raising
    # +Hecks::PathTraversalDetected+ if the resolved path escapes the root.
    # Guards against +../+ traversal, absolute paths, and null bytes.
    #
    # @param root [String] the directory the write must stay within
    # @param relative_path [String] the path to resolve (relative to root)
    # @return [String] the absolute resolved path when safe
    # @raise [Hecks::PathTraversalDetected] if the path escapes root or contains
    #   a null byte
    #
    # @example
    #   Hecks::Utils.safe_path!("/tmp/out", "lib/pizza.rb")
    #   # => "/tmp/out/lib/pizza.rb"
    #
    #   Hecks::Utils.safe_path!("/tmp/out", "../etc/passwd")
    #   # raises Hecks::PathTraversalDetected
    def safe_path!(root, relative_path)
      raise PathTraversalDetected.new(attempted_path: relative_path, output_dir: root) if relative_path.include?("\0")
      expanded_root = File.expand_path(root)
      full = File.expand_path(relative_path, expanded_root)
      unless full.start_with?(expanded_root + File::SEPARATOR) || full == expanded_root
        raise PathTraversalDetected.new(attempted_path: relative_path, output_dir: root)
      end
      full
    end

    # Remove a constant from a module if it exists.
    #
    #   Hecks::Utils.remove_constant(:PizzasDomain)
    #
    def remove_constant(name, from: Object)
      from.send(:remove_const, name) if from.const_defined?(name, false)
    end

    # Start tracking constants for the current scope (test, REPL session).
    # Call before a test runs to snapshot what's already tracked.
    #
    def begin_constant_tracking
      @tracked_constants ||= []
      @tracking_watermark = @tracked_constants.size
    end

    # Track a constant that was hoisted to Object.
    #
    #   Hecks::Utils.track_constant(:PizzasDomain)
    #
    def track_constant(name)
      @tracked_constants ||= []
      @tracked_constants << name.to_sym
    end

    # Remove constants added since the last begin_constant_tracking call.
    # Only cleans up what the current scope created, not shared setup.
    #
    def cleanup_constants!
      @tracked_constants ||= []
      watermark = @tracking_watermark || 0
      to_remove = @tracked_constants[watermark..]
      to_remove&.each { |name| remove_constant(name) }
      @tracked_constants = @tracked_constants[0...watermark]
      @tracking_watermark = watermark
      remove_constant(:APP)
    end
  end
end
