# Hecks::Parity::Fuzz::Generator::Renderer
#
# Purpose: turn the generator's structured aggregate/policy hashes
# into .bluebook source text. Both parsers round-trip the result
# (verified by the driver's self-test on every seed).
#
# Split out from generator.rb for the 200-line limit.
#
# [antibody-exempt: differential fuzzer per i30 plan — retires when
# fuzzer ports to bluebook-dispatched form via hecks-life run]

module Hecks
  module Parity
    module Fuzz
      module Generator
        module Renderer
          module_function

          def render_bluebook(name, aggregates, policies)
            out = +""
            out << "Hecks.bluebook \"#{name}\", version: \"2026.04.22.1\" do\n"
            out << "  vision \"Generated by i30 differential fuzzer.\"\n\n"
            aggregates.each { |a| out << render_aggregate(a) << "\n" }
            policies.each    { |p| out << render_policy(p)    << "\n" }
            out << "end\n"
            out
          end

          def render_aggregate(agg)
            out = +""
            out << "  aggregate \"#{agg[:name]}\", \"Generated aggregate\" do\n"
            agg[:attrs].each do |a|
              out << "    attribute :#{a[:name]}, #{a[:type_src]}\n"
            end
            out << "\n"
            agg[:commands].each { |c| out << render_command(c, agg) }
            if agg[:lifecycle]
              out << render_lifecycle(agg[:lifecycle])
            end
            out << "  end\n"
            out
          end

          def render_command(cmd, agg)
            out = +""
            out << "    command \"#{cmd[:name]}\" do\n"
            out << "      role \"System\"\n"
            out << "      reference_to(#{agg[:name]})\n" if cmd[:self_ref]
            # Intentionally do NOT declare `attribute :<field>` for
            # mutation fields — that would trigger auto-input-copy on
            # new states and overwrite the mutation's result (a real
            # runtime divergence outside this fuzzer's v1 scope).
            cmd[:given_attrs].each do |a|
              out << "      given(\"#{a[:name]} below ceiling\") { #{a[:name]} < 100 }\n"
            end
            cmd[:mutation_attrs].each do |a|
              out << "      then_set :#{a[:name]}, increment: 1\n"
            end
            out << "      emits \"#{cmd[:emits]}\"\n"
            out << "    end\n\n"
            out
          end

          def render_lifecycle(lc)
            out = +""
            out << "    lifecycle :#{lc[:field]}, default: \"#{lc[:default]}\" do\n"
            lc[:transitions].each do |t|
              out << "      transition \"#{t[:command]}\" => \"#{t[:to]}\", from: \"#{t[:from]}\"\n"
            end
            out << "    end\n"
            out
          end

          def render_policy(p)
            out = +""
            out << "  policy \"#{p[:name]}\" do\n"
            out << "    on \"#{p[:on_event]}\"\n"
            out << "    trigger \"#{p[:trigger]}\"\n"
            out << "  end\n"
            out
          end
        end
      end
    end
  end
end
